### ISSUE TITLE
从adobe animate导出，绝对吊炸天，超好用

### ISSUE THREAD

**Issue by evenle** [leaferjs/ui#10]
如果支持从adobe animate导出，绝对吊炸天，超好用
参考这个  
https://github.com/pixijs/animate-extension
这样就可以快速适配动画，也相当于有了编辑器可以操作代码

**Comment by leaferjs** [comment]
收到建议

**Comment by yh4922** [comment]
感觉有点类似这个 https://github.com/Tencent/libpag

**Comment by ks-zc** [comment]
> 感觉有点类似这个 https://github.com/Tencent/libpag

pag目前需要wasm和webgl，低端机没法支持，而且pag并没有它描述的那么好，体积很大(示例文件动画很简单，但文件不小)，而且他的示例pag文件(雪人)，明显掉帧
