### ISSUE TITLE
有办法设置画布的显示尺寸和实际尺寸吗

### ISSUE THREAD

**Issue by Tianj0o** [leaferjs/ui#100]

**Comment by leaferjs** [comment]
自己定义一个单位转换的方法就行

**Comment by Tianj0o** [comment]
不是 比如canvas设置width height 500 但是我只想要在网页上显示style 100*100 ,现在如果我手动修改canvas的style 元素的定位什么的都有问题 主要还是想要不管什么大小的屏幕 画布显示大小自适应 但是画布真实大小是默认设置的

**Comment by leaferjs** [comment]
可以通过pixelRatio设置

**Comment by Tianj0o** [comment]
谢谢 现在就是使用pixelRatio解决的
