### ISSUE TITLE
旋转图形时旋转的icon实时更新是否正常？

### ISSUE THREAD

**Issue by 313812245** [leaferjs/ui#102]
![20240316215539](https://github.com/leaferjs/ui/assets/17757813/2ca8df1b-2d5f-4f80-99ef-ca55aff322e7)

所有鼠标的图形都是重新获取的，应该读取过的缓存一份

**Comment by leaferjs** [comment]
收到，谢谢反馈～， 属于正常现象，旋转/resize光标是跟随元素角度实时变化的（html的光标不具备旋转功能，只能通过加载新的光标模拟），测试过性能不会有太大的影响，后面我们再关注看看

**Comment by leaferjs** [comment]
已经增加了生成旋转图标的缓存机制，旋转光标最多只缓存180个
