### ISSUE TITLE
[图形编辑器][animeJS]使用animeJS之后图形编辑失效

### ISSUE THREAD

**Issue by illlyas** [leaferjs/ui#103]
`
const app = new App({
            view: ref.current as never,
            editor: {},
            zoom: {
                min: 0.5,
                max: 2
            }
        });
        const rectMap: Record<never, never> = {}
        new Array(1).fill({}).map((_i, index) => {
            const r = new Rect({
                editable: true,
                fill: '#ccc',
                x: 1 + index,
                y: 1 + index,
                width: 100,
                height: 100
            });
            rectMap[index] = r;
            app.tree.add(r);
        })

        app.tree.add(new Ellipse({
            width: 200,
            height: 200,
            editable: true,
            x: 200,
            y: 200,
            fill: "#777888"
        }))

        setTimeout(() => {
            forEach(rectMap, (r) => {
                const data = {
                    x: r.x,
                    y: r.y,
                    cornerRadius: 0,

                    fillR: 0x32, // = #32cd79
                    fillG: 0xcd,
                    fillB: 0x79,
                }
                anime({
                    targets: data,
                    keyframes: [{
                        x: 500 + r.x,
                        fillR: 0xff, // = #ffcd00
                        fillG: 0xcd,
                        fillB: 0x00,
                        easing: 'easeInOutQuad' // 动画类型
                    }, {
                        y: 500 + r.y,
                        cornerRadius: 50,
                        fillR: 0x32, // = #32cd79
                        fillG: 0xcd,
                        fillB: 0x79,
                    }],
                    loop: false,
                    duration: 3000,
                    easing: 'easeInOutQuad',
                    direction: 'alternate', // 循环往复
                    update: () => {
                        const {x, cornerRadius, fillR, fillG, fillB, y} = data;
                        r.set({x, y, cornerRadius, fill: toColor(fillR, fillG, fillB)});
                    }
                })
            })

        }, 3000);
`

动画结束之后就无法点选画布上的元素了

**Comment by leaferjs** [comment]
你写的动画导致AnimeJS出了问题，一直卡住cpu在执行， 你试试文档里的例子就不会有这个问题（看来后面还是得我们自己出一套动画库）

**Comment by illlyas** [comment]
> 你写的动画导致AnimeJS出了问题，一直卡住cpu在执行， 你试试文档里的例子就不会有这个问题（看来后面还是得我们自己出一套动画库），再改改看，监测一下cpu的情况

找到原因了，使用anime的地方关键帧属性没有完全补齐，第一个关键帧里没有y属性，第二个有，这样动画看起来没啥问题也不报错，但实际上已经出问题了。

非常期待官方自己出一套动画库，太有用了
