### ISSUE TITLE
关于leafer画板限制无限滚动以及缩放的问题

### ISSUE THREAD

**Issue by ALosee** [leaferjs/ui#108]
现在的leafer默认是可以无限滚动画板的，如果我需要限制滚动的范围，可以通过Drag事件来计算x、y坐标来限制滚动范围，但是如果同时需要考虑缩放的问题，那么这个计算就变得没那么简单了，因为要保证缩放也限制一定的范围

**Comment by leaferjs** [comment]
安装滚动条插件可以避免找不到内容，另外，即将发布的新版本增加了类似网页的滚动限制配置，不知道是否能解决你的需求？

**Comment by leaferjs** [comment]
已支持限制滚动范围：

https://leaferjs.com/ui/guide/app/config.html#move-scroll-boolean-limit
