### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by HodgeWen** [leaferjs/ui#11]
- 缺乏引导, 应该从零开始搭建一个由简单到稍微不那么简单的实例, 并在这其中介绍一些API的作用
- 文档中相当多的示例无法提供相当直观的演示, 只有代码
- 更进一步希望在页面上可以直接编辑代码然后看到效果变更
- 菜单布局希望可以优化, 所有的API相关的专门收入到一个顶部导航栏下, 同时将上手和引导部分抽取出来
- 文档对各种术语的解释还不够详细

**Comment by leaferjs** [comment]
非常感谢你的建议，我们记录下了，我们现在在忙正式版的开发工作，后面会抽时间再完善这一块的，包括联合开发者提供一些demo
