### ISSUE TITLE
显示图片失败 

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#111]
![image](https://github.com/leaferjs/ui/assets/34226979/9c42ee4b-e357-43eb-9ccb-ff0dc993d77a)

![image](https://github.com/leaferjs/ui/assets/34226979/1149e179-962c-4b2d-8733-affe51b230c3)

```
   const image = new LeaferUI.Image({
                url: '/images/leafer.jpg',
                draggable: false,
            });
            image.once(ImageEvent.ERROR, function (e) {
                console.log(e.error)
            });
            app.tree.add(image);
            const rect = new Rect({
                fill: {
                    type: 'image',
                    url: '/images/leafer.jpg',
                    mode: 'strench'
                },
                stroke: 'red',
                draggable: true,
            })
            app.tree.add(rect);
```

/images/leafer.jpg 这个图片在我本地是可以访问的 
![image](https://github.com/leaferjs/ui/assets/34226979/a0043442-43fc-41d2-8609-31bd6a4e750e)

**Comment by leaferjs** [comment]
浏览器原生的Image被 const {..., Image, ...} = LeaferUI 覆盖了，把这里的Image去掉应该就好了
