### ISSUE TITLE
 浏览器中 ,怎么 自定义元素

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#115]
<script type="module">
  import { Leafer } from 'https://unpkg.com/leafer-ui@1.0.0-rc.19/dist/web.module.min.js'
</script>

这里怎么 自定义元素

**Comment by leaferjs** [comment]
自定义元素里有js版本的，切换下代码标签
![image](https://github.com/leaferjs/ui/assets/83396016/9c43dfc3-139a-4be1-bb02-ea1a53911400)
