### ISSUE TITLE
实现流程图有什么难点

### ISSUE THREAD

**Issue by nanfb** [leaferjs/ui#116]
我们项目使用antv X6实现的流程图，好处是很多东西不用自己实现，而且社区也很活跃，但是由于X6是svg实现的，在巨量节点下内存和性能问题不容忽视，如果我想用leafer实现，有什么难点吗？主要是对连线的编辑，修改等，path的修饰点等，参考这个网站效果https://wakak.shop/ 这是X6实现的一个简易demo。

**Comment by leaferjs** [comment]
主要难点应该就是连线、路径编辑功能，不过后面会有相关插件，掌握坐标系、矩阵、元素包围盒等基础知识，就能自己实现这些～
