### ISSUE TITLE
最佳实践

### ISSUE THREAD

**Issue by vannvan** [leaferjs/ui#12]
有没有考虑提供最佳实践的计划呀，比如这个库其实是可以实现可视化编辑器的能力的，可以提供一个相对完整的综合案例

**Comment by leaferjs** [comment]
有考虑的，后面会联合开发者一起提供的案例

**Comment by happysmile12321** [comment]
> 有考虑的，后面会联合开发者一起提供demo案例

我能加入进来么？我目前在开发白板类应用。

**Comment by happysmile12321** [comment]
@leaferjs 目前架子已经搭建好，但是渲染效果不太理想。

**Comment by happysmile12321** [comment]
作者大大，您提供的微信群满员了，提示只能群主邀请进群。

**Comment by leaferjs** [comment]
@happysmile12321 谢谢反馈，确实是满员了，建了个技术交流2群，可以加入这个
![wechat-group](https://github.com/leaferjs/ui/assets/83396016/94cd8a62-66d2-4732-9eb0-7858259a1cda)

**Comment by icezeros** [comment]
二维码过期了

**Comment by icezeros** [comment]
@leaferjs 提示二维码过期了

**Comment by leaferjs** [comment]
谢谢反馈，请前往官网扫描最新的二维码：https://leaferjs.com/ui/guide/
