### ISSUE TITLE
export 导出模糊应该怎么解决

### ISSUE THREAD

**Issue by hlovingness** [leaferjs/ui#122]
leafer.export(`png`, { pixelRatio: 3, scale: 1  })

还是模糊，设置 scale= 2，会在图片中间出现个？号，感觉是失败了

**Comment by hlovingness** [comment]
就是有图片资源，而且图片里面内容比较丰富，然后看着就很模糊，我提高一下图片质量吧，是用的最新版本

**Comment by leaferjs** [comment]
ok,  那应该是放大了图片导致的
