### ISSUE TITLE
怎么设置默认的位移？

### ISSUE THREAD

**Issue by wumingluren** [leaferjs/ui#123]
左上角默认是0x0
果子米默认是负数，看了下没找到在哪设置。
![image](https://github.com/leaferjs/ui/assets/41581133/224d6cf3-ad59-4f05-873f-4dd7f42c5dba)

**Comment by leaferjs** [comment]
应该是默认移动了画布，用这个：app.tree.zoomLayer.x

**Comment by wumingluren** [comment]
> 应该是默认移动了画布，用这个：app.tree.zoomLayer.x

这个手动赋值确实可以，已解决。
