### ISSUE TITLE
需求：是否考虑在创建画布时即可设置scale 属性

### ISSUE THREAD

**Issue by a-boom** [leaferjs/ui#127]
现象：微信小程序，在375x375 的canvas上初始化宽高为 1000x1000 的画布，监听 rect 的 pointerEvent, 发现触发元素 与实际手指划过的元素位置存在明显偏移

**Comment by leaferjs** [comment]
这个警告你有注意看到吗？默认是可以传scale的， new Leafer({view...}, {scale: 0.3})

![image](https://github.com/leaferjs/ui/assets/83396016/00789880-894a-4a53-85a1-a8727da89135)

**Comment by a-boom** [comment]
看到了   需求简单不用使用离屏画布
