### ISSUE TITLE
视图   中 zoom  in 或 out 是不是可以 指定 每次 变化的值  ，  比果    -、+ 10%

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#129]
如题

**Comment by leaferjs** [comment]
可以自己指定缩放比例满足

**Comment by leaferjs** [comment]
zoom in / out目前采用的是行业最佳实践，建议不要改动

**Comment by canbaoSama** [comment]
我尝试了一下开启滚轮的缩放是可以正常使用的，但是我使用app.tree.zoom(2)这样的方式不能成功，请问大佬这是为啥，我的app创建如下
app = new App({
        view: leaferViewRef.value,
        hitSelf: false,
        editor: {
            rotateable: false,
        },
        move: {
            holdRightKey: true,
        },
        wheel: {
            zoomMode: 'mouse',
            preventDefault: true,
        },
        zoom: { min: 0.02, max: 256 },
    })
