### ISSUE TITLE
关于 Fill 填充的两点建议

### ISSUE THREAD

**Issue by oubenruing** [leaferjs/ui#13]
1.框架本身实现了Image的封装，图形以及路径的填充如果能支持自己的对象会不会更好？
```ts
import { Leafer, Image } from 'leafer-ui'

const leafer = new Leafer({ view: window })

const image = new Image({  
    url: '/image/leafer.jpg',
})

const rect = new Rect({
    width: 100,
    height: 100,
    // fill 直接传入 image对象
    fill: image
})

leafer.add(rect)
```
2.重复方式 增多支持 repeat-x repeat-y

```diff
-export type IImagePaintMode = 'cover' | 'fit' | 'strench' | 'clip' | 'repeat'
+export type IImagePaintMode = 'cover' | 'fit' | 'strench' | 'clip' | 'repeat'| 'repeat-x'| 'repeat-y'
```

**Comment by leaferjs** [comment]
谢谢建议！

1. 目前已经支持了图像填充，还可以用于描边：http://localhost:5173/ui/guide/property/paint/image.html
2. 目前主流的UI设计软件都没有支持'repeat-x'与 'repeat-y'，可能是实际用到会非常少，repeat已经能满足要求，我们再思考下，如果有很多实际需要的场景，我们再考虑加上

**Comment by oubenruing** [comment]
> 谢谢建议！
> 
> 1. 目前已经支持了图像填充，还可以用于描边：https://leaferjs.com/ui/guide/property/paint/image.html
> 2. 目前主流的UI设计软件都没有支持'repeat-x'与 'repeat-y'，可能是实际用到会非常少，repeat已经能满足要求，我们再思考下，如果有很多实际需要的场景，我们再考虑加上

关于第一点：可能我表述不太清楚
我看到文档有写到fill，但参数是传入一个 url；我的期望是比如我有一个Path，我想给他传入一个 本库提供的 实例化的Image对象
```diff
const rect = new Rect({
    width: 100,
    height: 100,
-    fill: {  
-        type: 'image',
-        url: '/image/leafer.jpg'
-    }
+ fill: image,
})
```

第二点：canvas本身createPattern也是支持'repeat-x'与 'repeat-y'的，其实只需要扩充一个参数即可。

感谢。

**Comment by leaferjs** [comment]
谢谢反馈，明白你的意思了，可以少写代码、少创建对象，内存方面目前是会共用同一个Image的原始对象
