### ISSUE TITLE
关于英文版

### ISSUE THREAD

**Issue by SWHL** [leaferjs/ui#130]
从[绝境中盛开，一位独立开发者的故事](https://mp.weixin.qq.com/s/S8MjHZog_2RFl_yYdoN44g)文章中看到作者这个项目，很棒。

建议可以搞搞英文版的宣传和英文版的README、官网等。我发现国内赞助环境差一些，国外好一些。

**Comment by leaferjs** [comment]
哈哈哈，好嘞，谢谢建议，目前国内凑集到的赞助能缓解一下，正在全力开发正式版，计划正式版之后就开始启动翻译工作～
