### ISSUE TITLE
ImagePaint 中有没有类似  background-position 的属性 

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#131]
如题

**Comment by leaferjs** [comment]
用clip模式， 通过x, y定位

**Comment by 3400442579** [comment]
这个不太好现实居中平铺，平铺的第一张在中间，Leafer 宽高 是会变化的

**Comment by leaferjs** [comment]
那估计得后面添加支持才行

**Comment by leaferjs** [comment]
图片填充已增加了 around 参数，可以实现这个效果：
https://leaferjs.com/ui/guide/property/paint/image.html#around-idirection
