### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by yoohoolai** [leaferjs/ui#133]
微信小程序里加入Rect，如下图代码，1是发现点击事件不生效；2是Rect的长宽相等，出现的图形是一个长方体

![微信图片_20240425160634](https://github.com/leaferjs/ui/assets/17917474/cafbbb11-c4dc-47b1-9438-1c9ee983a8a0)

![微信图片_20240425161214](https://github.com/leaferjs/ui/assets/17917474/a268ac52-d46b-4a84-bbca-6f54921dfdd6)

**Comment by leaferjs** [comment]
应该是遮挡住了，小程序端做交互，建议用webview组件做， iOS端官方有个bug，我们无法绕过，等后期再看看。

**Comment by Qiu-Jun** [comment]
> 应该是遮挡住了，小程序端做交互，建议用webview组件做， iOS端官方有个bug，我们无法绕过，等后期再看看。

啥bug，影响使用吗？  webview体验上有点差

**Comment by leaferjs** [comment]
> > 应该是遮挡住了，小程序端做交互，建议用webview组件做， iOS端官方有个bug，我们无法绕过，等后期再看看。
> 
> 啥bug，影响使用吗？ webview体验上有点差

会导致ios端用不了复杂的交互功能，只能画离屏海报，看下这个问题：

https://developers.weixin.qq.com/community/develop/doc/000264fc838f08be4d6002d9166c00

**Comment by Qiu-Jun** [comment]
> > > 应该是遮挡住了，小程序端做交互，建议用webview组件做， iOS端官方有个bug，我们无法绕过，等后期再看看。
> > 
> > 
> > 啥bug，影响使用吗？ webview体验上有点差
> 
> 会导致ios端用不了复杂的交互功能，只能画离屏海报，看下这个问题：
> 
> https://developers.weixin.qq.com/community/develop/doc/000264fc838f08be4d6002d9166c00
> 
> 文档中也有警告：
> 
> https://www.leaferjs.com/ui/guide/miniapp/start.html#%E6%B3%A8%E6%84%8F

能简单使用就好，等官方修复，我还记得版本更新的api在ios还是安卓，时有效时失效，已经好几年了

**Comment by leaferjs** [comment]
目前已支持在ios端简单使用了～
