### ISSUE TITLE
使用的是@leafer-ui/node，安装@leafer-in/arrow后报错，请大佬考虑下兼容

### ISSUE THREAD

**Issue by wr1688** [leaferjs/ui#136]
![image](https://github.com/leaferjs/ui/assets/91103311/96fe201b-26c1-4bdd-ba4e-76fa46a02204)
前端leafer-ui使用@leafer-in/arrow没问题

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复，等待新版本发布～

**Comment by leaferjs** [comment]
已上线完成～
