### ISSUE TITLE
electron can't load local image

### ISSUE THREAD

**Issue by chenyuyu118** [leaferjs/ui#137]
I'm trying to use leafer in electron,but it can't load local image with specificied protocol which can be successfully loaded by canvas or other web image load way.

![image](https://github.com/leaferjs/ui/assets/55904740/884ebe1f-ca2a-4cec-8971-5997e3e60777)

![image](https://github.com/leaferjs/ui/assets/55904740/96e52ffb-76cd-4ce8-8d9e-0a98edaf73d3)

**Comment by leaferjs** [comment]
![image](https://github.com/leaferjs/ui/assets/83396016/70b08622-6572-49ee-b7da-7ece9c41a386)

默认添加了一个?leaf后缀，设为空即可解决问题

import { Platform } from 'leafer-ui'
Platform.image.suffix = ''
