### ISSUE TITLE
可以像蓝湖那样生成标注线吗？应该怎么搞，可以给个思路吗

### ISSUE THREAD

**Issue by hlovingness** [leaferjs/ui#139]

**Comment by leaferjs** [comment]
可以的，很早就支持了，Wodisign产品就是案例，标注一般是单独在一个层上，通过canvas的原生context绘制的

**Comment by hlovingness** [comment]
明白了，leaferjs 可以直接使用吗？是用哪个方法呢

**Comment by leaferjs** [comment]
可以看一下Leafer的文档，上面挂着一个canvas属性：

 https://leaferjs.com/ui/guide/display/Leafer.html#canvas-ileafercanvas
