### ISSUE TITLE
关于Text分词分组的小想法

### ISSUE THREAD

**Issue by kooriookami** [leaferjs/ui#14]
Hi，目前Text组件会把一个英文单词当做一个整体char，而CJK字符如汉字会单独拆分成char，我的小想法是提供一个文本分组的正则，让用户自己决定怎么分词分组。比如定义一个正则分组属性`groupPattern: '/\[.*?]/g'`，表明`[]`中的文字会当做一个整体char，这样能够控制换行效果。具体的应用场景可以模拟html中ruby与rt的作用，实现文本注音。设想如果ruby换行，那rt就无法注音了。

下图是`Text.textDrawData`属性
![微信图片_20230717172606](https://github.com/leaferjs/ui/assets/38392315/691a17d6-8c6d-4f1b-b1da-402f8c53f316)

具体期望写法：
```js
const text = new Text({
  width: 400,
  fill: 'black',
  fontSize: 24,
  lineHeight: 48,
  text: 'congratulation[泥嚎哇]',
  textAlign: 'justify',
  groupPattern: '/\[.*?]/g',
})
```
分词分组后可以是下图效果
![image](https://github.com/leaferjs/ui/assets/38392315/ada3405d-95b3-40ab-8567-8bc69d357b70)

以上是对于Text的一个小想法，如果有更加合适的方案可以一起讨论。

**Comment by kooriookami** [comment]
提供一个demo：
https://jsfiddle.net/Lf2hw83s/14/
![image](https://github.com/leaferjs/ui/assets/38392315/66f0c45e-4e31-4a7a-adce-e05541160e37)

**Comment by leaferjs** [comment]
收到

**Comment by kooriookami** [comment]
目前换行分词已经实现，可以参照：https://github.com/kooriookami/compress-text/blob/master/src/utils/split-break-word.js
大部分代码逻辑可以与LeaferUI复用，感觉可以整合进LeaferUI作为一个单独的方法。
