### ISSUE TITLE
如何在图形编辑器时，缩放图片大小时，保持锁定比例？

### ISSUE THREAD

**Issue by 826327700** [leaferjs/ui#144]
尝试找了好久的文档，没找到关于这个的设置，求指点...

**Comment by leaferjs** [comment]
给编辑器配置lockRatio: true 可以实现

https://leaferjs.com/ui/guide/plugin/editor/config.html#lockratio-boolean-corner

**Comment by MD777-creator** [comment]
开发大大，我想问下，只是初始化配置时才生效嘛？我后期改动后好像并不生效

**Comment by leaferjs** [comment]
用最新版本， 之前有个bug， 再不行的话手动更新一下app.editor.update()
