### ISSUE TITLE
关于性能提升的一些疑问，望解答

### ISSUE THREAD

**Issue by rookieLink** [leaferjs/ui#15]
看官网的介绍这里和其他框架的对比，有几处疑问，辛苦作者能解惑一下

1、渲染速度比其他渲染引擎提升这么多的原因是什么，核心架构相比其他的点有什么特别的优势点

2、运行怎么做到占用这么小的，是其他框架对于这里额外存储了一些内容吗？

3、想学习一下库的实现，本地想跑代码试试，能出个本地跑库的文档不，还有各个目录负责的功能

**Comment by leaferjs** [comment]
目前主要是创建速度和布局速度，减少了很多内存开销和计算，渲染速度还没有做很深的优化，这篇文章做了比较详细的分析：https://juejin.cn/post/7256386855721074747?searchId=202307181721344FAA12C56491A0B139EF

我们最近开发的任务还比较重，等正式版出来后，会开放本地跑库的代码哈
