### ISSUE TITLE
修改boxSelect貌似在初始状态下无效

### ISSUE THREAD

**Issue by rojer95** [leaferjs/ui#150]
`app.editor.config.boxSelect = true;` 需要激活过selector，修改配置才能生效，比如下面这个录屏

https://github.com/leaferjs/ui/assets/20662049/b11a393e-f8d9-4455-857c-4ef4b58ecced

第1、2次画矩形时候，会出现蓝色的boxSelect，即使把 `.editor.config.boxSelect = false;`了。
后面激活过一次 ，就不会出现蓝色的boxSelect了

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复，请安装rc28版本～
