### ISSUE TITLE
当双击字体进入编辑状态时，字体大小变小了

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#151]
如下图，当双击字体进入编辑状态时，字体大小变小了，是需要配置什么属性不(版本为最新版1.0.0-rc.28)？

![image](https://github.com/leaferjs/ui/assets/129353743/f6d947f2-6c59-4df4-b7ee-f3168db1329d)

**Comment by leaferjs** [comment]
目前还在公测中，有公测权限的能用，之前我们搞了一波赞助，回馈一下用户。不稳定的时候，同时反馈问题的人太多，会服务不过来，等过一段时间稳定了，会开放给所有人使用～
