### ISSUE TITLE
@leafer-in/editor 和 @leafer-in/html 冲突

### ISSUE THREAD

**Issue by canbaoSama** [leaferjs/ui#152]
我安装@leafer-in/editor  使用正常，但是再次安装@leafer-in/html 后编辑器无法初始化，报错 ‘Creator.editor is not a function‘，卸载@leafer-in/html 后再次正常

**Comment by leaferjs** [comment]
检查一下插件版本是不是都是一样的，你这个问题可能是出现了两个不同版本导致的，或者尝试一下这个方法：
![8061719198880_ pic](https://github.com/leaferjs/ui/assets/83396016/9b5037fd-76e8-4151-9150-9744c8c70693)

**Comment by canbaoSama** [comment]
嗯嗯，我试了下，全部更新为1.0.0-rc.28版本是可以的，多谢大佬
