### ISSUE TITLE
HTMLText在box内无法使用，特殊情况下可以生效

### ISSUE THREAD

**Issue by canbaoSama** [leaferjs/ui#154]
如果我在一个box里的children里使用HTMLText标签，则不能生效，会报错list$1[tag] is not a constructor
{
            tag: 'HTMLText',
            text: '<i style="color: red; font-weight: bold;">Welcome</i> to <i style="color: rgb(50,205,121); font-size: 30px">LeaferJS</i>',
}
      
但是如果我在这个页面添加如下的创建方式，则box里HTMLText又可以正常使用
const textL = new HTMLText({
    text: `<i style="color: red; font-weight: bold;">8</i>`,
})

请问大佬是不是引用有些问题啊

**Comment by leaferjs** [comment]
第一种情况，应该是没有引入html包

**Comment by canbaoSama** [comment]
我引入了，第二种情况和第一种情况是在同一个页面，如果我添加了第二种情况的代码第一种也生效，但是不添加则第一种失败

**Comment by leaferjs** [comment]
import '@leafer-in/html'

这样引入

**Comment by leaferjs** [comment]
import { HTMLText } from '@leafer-in/html'    这样引入，没有实例化HTMLText，编译器不会把这个包的代码打包进来

**Comment by canbaoSama** [comment]
好吧，我傻了，忘记了
