### ISSUE TITLE
有没有可以让box变换颜色的动画

### ISSUE THREAD

**Issue by zzzz-bang** [leaferjs/ui#155]
目前看都是移动、旋转等，有没有可以一直变化颜色的动画呢

**Comment by leaferjs** [comment]
有啊，看一下这个例子：

https://leaferjs.com/ui/plugin/combine/animejs/

**Comment by leaferjs** [comment]
动画这块还没细化，可以先用自己熟悉的第三方动画库实现

**Comment by zzzz-bang** [comment]
好的好的
