### ISSUE TITLE
scaleResize(1,-1)镜像不生效

### ISSUE THREAD

**Issue by canbaoSama** [leaferjs/ui#156]
我按照下方的方法使用镜像，但是group内部的元素不展示了，实际上是存在的，内部的x，y，scaleX,scaleY等值都没发生变化，再次调用则回到原有位置，这是为什么呢？
group.scaleResize(imgControlData.value.scale3d.x, 0 - imgControlData.value.scale3d.y)

**Comment by leaferjs** [comment]
这个不支持镜像呀， 镜像用group.scaleY = -1就行

**Comment by canbaoSama** [comment]
嗯嗯，后面我自己写了一下计算方法，但是是针对框选这类元素的，（如果是内部图片镜像的只能重新贴图了）

case ImgControlType.SWITCH_UP_DOWN: // 上下镜像
                app.tree.children[0]?.children?.forEach((box) => {
                    box.y = app.height - (box.y || 0) - (box.height || 0)
                })
                break
            case ImgControlType.SWITCH_LEFT_RIGHT:// 左右镜像
                app.tree.children[0]?.children?.forEach((box) => {
                    box.x = app.width - (box.x || 0) - (box.width || 0)
                })
                break
            case ImgControlType.ROTATE_LEFT:// 左旋转
                app.width = imgData.width
                app.height = imgData.height
                app.tree.children[0]?.children?.forEach((box) => {
                    const oldBox = {
                        x: box.x || 0,
                        y: box.y || 0,
                        width: box.width || 0,
                        height: box.height || 0,
                    }
                    box.x = oldBox.y
                    box.y = app.height - (oldBox.x + oldBox.width)
                    box.width = oldBox.height
                    box.height = oldBox.width
                })
                break
            case ImgControlType.ROTATE_RIGHT:// 右旋转
                app.width = imgData.width
                app.height = imgData.height
                app.tree.children[0]?.children?.forEach((box) => {
                    const oldBox = {
                        x: box.x || 0,
                        y: box.y || 0,
                        width: box.width || 0,
                        height: box.height || 0,
                    }
                    box.x = app.width - (oldBox.y + oldBox.height)
                    box.y = oldBox.x
                    box.width = oldBox.height
                    box.height = oldBox.width
                })
                break

**Comment by canbaoSama** [comment]
嗯嗯，后面我自己根据需求写了一下计算方法，多谢大佬回答了
