### ISSUE TITLE
移动有控制在边界内的api吗

### ISSUE THREAD

**Issue by zzzz-bang** [leaferjs/ui#157]
譬如移动一个rect，只能在leafter范围内移动，超出这个范围就移动不了限制住了。以及创建的没有拖拽放大缩小功能，这个是有需要专门的配置吗

**Comment by zzzz-bang** [comment]
创建的没有拖拽放大缩小功能里面嵌套了一堆children，我用了下演示里的例子 也是没有拖拽拉长放大缩小功能的

**Comment by leaferjs** [comment]
> 譬如移动一个rect，只能在leafter范围内移动，超出这个范围就移动不了限制住了。以及创建的没有拖拽放大缩小功能，这个是有需要专门的配置吗
有，用dragBounds:

https://leaferjs.com/ui/reference/property/draggable.html#dragbounds-iboundsdata-parent

创建拖拽放大缩小，需要安装图形编辑器插件。
