### ISSUE TITLE
建议增加用顶点数组描述多边形的API

### ISSUE THREAD

**Issue by levalup** [leaferjs/ui#16]
当前使用的 `1.0.0-beta.4` 的 `leafer-ui` 中 Polygon 图形绘制的只有正多边形。而本人当前工作中遇到的场景，多边形图形都是用顶点描述的不规则多边形（图像数据标注）。当然一般的多边形都是不规则多边形的场景居多。
当然可以用 Path 去表示多边形，效果和结果也类似。

但是从 API 设计的角度建议增加使用顶点去描述一个多边形的接口，方便数据结构的对应和使用。
类似 `new Polygon({points: [10, 20, 30, 40]})` 或 `new Polygon({points: [{x: 10, y: 20}, {x: 30, y: 40}]})`。

本人就是翻找 API 发现 Polygon 居然不支持顶点的多边形，然后通读的 API 才找到 Path 去做，还一度以为做不到……。
简单翻了源码发现其实都是一样的东西。希望接口能丰富一下，迎合一下偏向其他领域过来的接口习惯。

**Comment by leaferjs** [comment]
谢谢反馈，建议已收到

**Comment by leaferjs** [comment]
已开发完成，等待新版发布～

 Polygon和Line新增points 和 curve属性， curve可以将线条转成平滑曲线，并支持设置曲率。
