### ISSUE TITLE
镜像未按照中心进行翻转

### ISSUE THREAD

**Issue by canbaoSama** [leaferjs/ui#160]
我设置group.scaleX或group.scaleY时，画布并未按照中心进行翻转，group.scaleY会按照画布上方的边进行翻转，group.scaleX 则按照画布左方进行翻转

**Comment by leaferjs** [comment]
围绕一个点镜像，要用scaleOf() 方法，编辑器上也有一个scaleOf()方法,  看下文档

**Comment by canbaoSama** [comment]
可以，谢谢大佬
