### ISSUE TITLE
text 的 textdecoration 文档描述不一至

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#166]
https://www.leaferjs.com/ui/reference/property/Text.html#textdecoration-itextdecoration

type ITextDecoration = 'none' | 'strikethrough' | 'underline'    // 这个没有效果

https://www.leaferjs.com/ui/reference/display/Text.html#textdecoration-itextdecoration

type ITextDecoration =
  | 'under' // 下划线
  | 'delete' // 删除线
  | 'none'

**Comment by leaferjs** [comment]
第一个咋被你搜索出来了（这个是早期的，我删除一下），以第二个为准哈～

**Comment by 3400442579** [comment]
在搜索框那 输入 就会出来 两个连接，今天试了一下，只有一个了 ，但连接还是可以访问
