### ISSUE TITLE
如何获取画布中，当前正在被选中的元素？

### ISSUE THREAD

**Issue by 826327700** [leaferjs/ui#168]
我正在将旧项目的功能(基于fabric.js) 迁移到leafer-ui，好多api还不熟悉，想请教一下：

1.类似于fabric中的getActiveObject()，在leafer中是否有对应的方法？
2.类似于fabric中的 selectedObj.center(); selectedObj.centerH(); selectedObj.centerV(); 在leafer中是否有对应的方法？

**Comment by 826327700** [comment]
自问自答一下，第1点已经找到了，原来在editor这个插件里：
leafer.editor.element

**Comment by leaferjs** [comment]
1. 当前选中的元素或列表： app.editor.target， 另外可通过 app.editor.list 获取纯数组的选中元素

**Comment by leaferjs** [comment]
2. 不太清楚具体含义，是不获取中心点坐标之类的？

**Comment by leaferjs** [comment]
> 自问自答一下，第1点已经找到了，原来在editor这个插件里： leafer.editor.element

单选时是对的，多选时用这个会有问题（这是一个模拟元素）

**Comment by 826327700** [comment]
> 2. 不太清楚具体含义，是不获取中心点坐标之类的？
> 
> 可以了解一下包围盒的知识，里面各种方法属性都有 https://leaferjs.com/ui/reference/property/bounds.html#bounds

首先感谢作者如此高效的回复。

第2点，其实是fabric内置对元素的公共辅助方法，调用selectedObj.center()，将元素移动到整个画布最中心位置。如果leafer没有类似这些辅助方法，也没关系，自己写吧，无非就是计算leafer画布的中心点x,y 然后obj.set({x,y})

**Comment by 826327700** [comment]
> 有一个功能很强大的视图控制插件可以了解一下：
> 
> https://www.leaferjs.com/ui/plugin/in/view/

好的，谢谢作者！
