### ISSUE TITLE
元素 的 flip 错误，node.flip is not a function

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#170]
![image](https://github.com/user-attachments/assets/66397319-ed31-4486-ae3d-b2a6e2f57f24)

![image](https://github.com/user-attachments/assets/ca782d73-689f-443e-b946-f576e28b5b28)

**Comment by leaferjs** [comment]
需要更新到最新版本～

**Comment by 3400442579** [comment]
已是 1.0.1 的，

**Comment by leaferjs** [comment]
你这个情况应该是没有更新成功，看看插件是不是也更新到了v1.0.1
![image](https://github.com/user-attachments/assets/07bc31bf-74db-4732-b0b1-70397feb3861)
