### ISSUE TITLE
控制台提醒

### ISSUE THREAD

**Issue by wangxiaogang94** [leaferjs/ui#171]
![image](https://github.com/user-attachments/assets/d80f9980-1020-4e6c-b936-4d3de8bec067)

**Comment by leaferjs** [comment]
检查官方插件有没有同步更新，这个是同事存在两个核心库版本导致的

**Comment by wangxiaogang94** [comment]
确实是因为有两个库导致的，一个是npmjs上的第三方库里带了一个，我自己也安装了一个，即使两个版本一样也会报这个问题。

**Comment by leaferjs** [comment]
![image](https://github.com/user-attachments/assets/e1799595-2644-4f1f-bb1f-d107291de8cb)
