### ISSUE TITLE
[小程序 uniapp环境]导入后使用就报错

### ISSUE THREAD

**Issue by Qiu-Jun** [leaferjs/ui#173]
版本： 1.0.1
代码：
```javascript
import { App, Leafer, Rect } from '@leafer-ui/miniapp'；
onReady(() => {
  const app = new App({
    view: 'leafer',
    mobile: true, // 优化手机端体验
    tree: { canvas: 'leafer-tree' }, // 需指定canvas
    sky: { canvas: 'leafer-sky', type: 'draw' },
    editor: {}, // 会自动创建 editor实例、tree层、sky层
    eventer: pages[pages.length - 1]
  })
  // const rect = new Rect({
  //   x: 100,
  //   y: 100,
  //   width: 100,
  //   height: 100,
  //   fill: '#32cd79',
  //   draggable: true
  // })
  // leafer.add(rect)
})
```
<img width="414" alt="image" src="https://github.com/user-attachments/assets/5e23ad56-0b41-496a-9abb-2339b3014559">

**Comment by Qiu-Jun** [comment]
注释new App就不报错了

**Comment by leaferjs** [comment]
图形编辑器的插件导入了吗？

**Comment by Qiu-Jun** [comment]
> 图形编辑器的插件导入了吗？

editor插件还要单独导入吗
```
const leafer = new Leafer({
    view: 'leafer',
    eventer: pages[pages.length - 1]
  })
```

直接new Leafer也报一样的错

**Comment by Qiu-Jun** [comment]
> 图形编辑器的插件导入了吗？

系统是mac, 基础库是最新的

**Comment by leaferjs** [comment]
发现是核心依赖包没有自动安装上， 手动 add一下这几个核心包试试

    "@leafer/core": "^1.0.1",
    "@leafer-ui/core": "^1.0.1",
    "@leafer-ui/draw": "^1.0.1",

**Comment by leaferjs** [comment]
> > 图形编辑器的插件导入了吗？
> 
> editor插件还要单独导入吗
> 
> ```
> const leafer = new Leafer({
>     view: 'leafer',
>     eventer: pages[pages.length - 1]
>   })
> ```
> 
> 直接new Leafer也报一样的错

需要单独导入

**Comment by Qiu-Jun** [comment]
> > > 图形编辑器的插件导入了吗？
> > 
> > 
> > editor插件还要单独导入吗
> > ```
> > const leafer = new Leafer({
> >     view: 'leafer',
> >     eventer: pages[pages.length - 1]
> >   })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 直接new Leafer也报一样的错
> 
> 需要单独导入



> 核心依赖包没有自动安装上， 手动 add一下这几个核心包试试
> 
> ```
> "@leafer/core": "^1.0.1",
> "@leafer-ui/core": "^1.0.1",
> "@leafer-ui/draw": "^1.0.1",
> ```

<img width="511" alt="image" src="https://github.com/user-attachments/assets/54e49d01-5cc0-409c-8e22-36185a80dce4">
重新安装了全部依赖，new Leafer 就报错了

**Comment by Qiu-Jun** [comment]
可以的话帮我看看是否是我的问题，我想如果能用原生的话就不想用webview的方法。[我的项目](https://github.com/Qiu-Jun/mine-pro)

**Comment by leaferjs** [comment]
地址访问不了啊，我刚亲自用uniapp又试了一遍，可以用的

> 可以的话帮我看看是否是我的问题，我想如果能用原生的话就不想用webview的方法。[我的项目](https://github.com/Qiu-Jun/mine-pro)

![image](https://github.com/user-attachments/assets/00b8e48c-e59b-4787-97b9-de8641237203)

**Comment by Qiu-Jun** [comment]
> 地址访问不了啊，我刚亲自用uniapp又试了一遍，可以用的
> 
> > 可以的话帮我看看是否是我的问题，我想如果能用原生的话就不想用webview的方法。[我的项目](https://github.com/Qiu-Jun/mine-pro)
> 
> ![image](https://private-user-images.githubusercontent.com/83396016/351176457-00b8e48c-e59b-4787-97b9-de8641237203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDY0MjMsIm5iZiI6MTcyMTcwNjEyMywicGF0aCI6Ii84MzM5NjAxNi8zNTExNzY0NTctMDBiOGU0OGMtZTU5Yi00Nzg3LTk3YjktZGU4NjQxMjM3MjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAzNDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYjgwNDU3ZWQ4YmZkMTc1Y2FlMjI3MWY0YjNmNTc1YjUwZTRlYzljNzdiZDUzNTVlNWIyNTdkOWM3OTQyNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gfq9ln2gMWio4YYfOTHfmNhjjhSto3XINh7JvYwgRWc)


emm.  我有空再看看

**Comment by Qiu-Jun** [comment]
> 地址访问不了啊，我刚亲自用uniapp又试了一遍，可以用的
> 
> > 可以的话帮我看看是否是我的问题，我想如果能用原生的话就不想用webview的方法。[我的项目](https://github.com/Qiu-Jun/mine-pro)
> 
> ![image](https://private-user-images.githubusercontent.com/83396016/351176457-00b8e48c-e59b-4787-97b9-de8641237203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDA4NzMsIm5iZiI6MTcyMjAwMDU3MywicGF0aCI6Ii84MzM5NjAxNi8zNTExNzY0NTctMDBiOGU0OGMtZTU5Yi00Nzg3LTk3YjktZGU4NjQxMjM3MjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMmIzYjlhYmI2NWQ5Yzg4ZWU4MDNhZjhlNzM1YTg4Zjc0NTBkMTU4MjFlYjFmNjA2MDM4YTM1Mzk2YmMzNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.87Xq29xFx63taNJNPJwLW051_h5wpd2yp9kdXKrTeWA)

我把代码拆出来，大佬有空拉去你电脑看看能不能跑。[代码](https://gitee.com/juneqiu/test)

**Comment by leaferjs** [comment]
收到
