### ISSUE TITLE
Canvas 和 Image 的默认 pixelRatio 不一至

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#175]
![image](https://github.com/user-attachments/assets/69a44bc9-9da7-4d69-91e0-d8d607bc5b4c)

**Comment by leaferjs** [comment]
谢谢反馈，下个版本统一下， 另外Canvas和Image都可以主动设置pixelRatio～

**Comment by leaferjs** [comment]
已优化，等待新版本发布～

**Comment by leaferjs** [comment]
新版本已发布～
