### ISSUE TITLE
有针对元素的(不是整个画布)，在移动端上双指缩放的功能吗？

### ISSUE THREAD

**Issue by 826327700** [leaferjs/ui#177]
目前测试双指缩放是缩放整个画布级别，当在App config中设置了zoom:{disabled:true}之后，画布禁用缩放了，但不知道如何针对画布里的元素进行双指缩放😅

**Comment by leaferjs** [comment]
看一下mobile配置(图形编辑器也需要设置手势控制）：

https://www.leaferjs.com/ui/reference/config/app/base.html#mobile-boolean

**Comment by 826327700** [comment]
> 看一下mobile配置(图形编辑器也需要设置手势控制）：
> 
> https://www.leaferjs.com/ui/reference/config/app/base.html#mobile-boolean

收到，已解决，谢谢！
