### ISSUE TITLE
希望完善该功能

### ISSUE THREAD

**Issue by Arc-zlz** [leaferjs/ui#178]
![MHQL_{}VR{XUFMXPLRWRAUX](https://github.com/user-attachments/assets/3064d1b5-51f4-44d8-bdb7-265dcaefc20a)
![E(_WZ5YP 9H QR}M$HKMHFC](https://github.com/user-attachments/assets/71acda8e-c46b-4c1b-9e6e-3cfded676ba0)
这个功能还是挺重要的,比如涉及复杂画图  就没办法复显(用户关闭后下次可以二次编辑)

**Comment by leaferjs** [comment]
收到～

**Comment by Arc-zlz** [comment]
嗯 感谢 现在我的思路是将算法生成的canvas地图转成images作为底图 放在最底部(图层) 然后上面的图层作为自由画笔工具的绘制图层 这样就可以回显  不过还没测试绘画工具绘画复杂的形状数据量怎么样

**Comment by leaferjs** [comment]
> 嗯 感谢 现在我的思路是将算法生成的canvas地图转成images作为底图 放在最底部(图层) 然后上面的图层作为自由画笔工具的绘制图层 这样就可以回显 不过还没测试绘画工具绘画复杂的形状数据量怎么样

已支持Canvas导出JSON数据用于回显， 等待新版本发布～

**Comment by leaferjs** [comment]
新版本已发布～
