### ISSUE TITLE
使用文本编辑插件后文字貌似渐变色不生效了

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#181]
文字填充渐变色如下：
{
    "type": "linear",
    "from": {
        "x": 0,
        "y": 0
    },
    "to": {
        "x": 1,
        "y": 1
    },
    "stops": [
        {
            "offset": "0.00",
            "color": "rgb(240, 255, 0)"
        },
        {
            "offset": "1.00",
            "color": "rgb(88, 207, 251)"
        }
    ]
}

分别效果如下图所示：
![image](https://github.com/user-attachments/assets/cb0ab63c-6bd0-4db8-bb34-253efca01918)

**Comment by leaferjs** [comment]
对的，编辑状态的文本，目前还没支持渐变色，后面会逐步支持哈～

**Comment by QmagicianEX** [comment]
> 对的，编辑状态的文本，目前还没支持渐变色，后面会逐步支持哈～

不处于待输入状态现在也不支持吗？

**Comment by leaferjs** [comment]
> > 对的，编辑状态的文本，目前还没支持渐变色，后面会逐步支持哈～
> 
> 不处于待输入状态现在也不支持吗？

这个应该支持啊，不支持的是进入编辑状态的dom文本（临时代替canvas文本进行输入）

**Comment by QmagicianEX** [comment]
知道什么原因了，在1.0.0-rc.24有对from/to进行了调整

fill: {
      "type": "linear",
      // IPointData 类型在1.0.0-rc.24版本后不生效了
      // "from": {
      //   "x": 0,
      //   "y": 0
      // },
      // "to": {
      //   "x": 1,
      //   "y": 1
      // },
      // 可采用IUnitPointData类型，需要添加 type属性
      "from": {
        type: 'percent',
        "x": 0,
        "y": 0
      },
      "to": {
        type: 'percent',
        "x": 1,
        "y": 1
      },
      // 或者采用IAlign类型
      // "from": 'top-left',
      // "to": 'bottom-right',
      "stops": [
        {
          "offset": 0.00,
          "color": "rgb(240, 255, 0)"
        },
        {
          "offset": 1.00,
          "color": "rgb(88, 207, 251)"
        }
      ]
    }
