### ISSUE TITLE
请教如何修改编辑器控制点？

### ISSUE THREAD

**Issue by 826327700** [leaferjs/ui#186]
![image](https://github.com/user-attachments/assets/f2b46019-7020-449a-82d9-653f2ab8a5d1)
如图，我想修改右上角控制点为自定义形状，且点击响应我自己的事件。例如，改造成删除图层按钮。

**Comment by 826327700** [comment]
> 支持直接配置控制点为按钮：
> 
> https://www.leaferjs.com/ui/plugin/in/editor/config.html#point-iboxinputdata-iboxinputdata
> 
> 控制点是一个Box, 可以根据情况自定义，或增加子元素

好的谢谢！同时我发现一个问题：
```
app.tree.add(rect)
app.editor.select(rect)// 主动调用选中元素，编辑器的边框控制条感觉有点异常
```
视频如下：

https://github.com/user-attachments/assets/233a442e-e91f-402b-8086-b511a09b6330

**Comment by leaferjs** [comment]
你是不是不小心创建了两个编辑器？

**Comment by leaferjs** [comment]
需要有能复现的代码才能排查的了，或者能复现的json结构～

**Comment by 826327700** [comment]
> 需要有能复现的代码才能排查的了，或者能复现的json结构～

我仔细排查了我的代码，发现是我写法的问题，换一种写法就可以了，很奇怪，算了，不纠结了。

**Comment by 826327700** [comment]
> 支持直接配置控制点为按钮：
> 
> https://www.leaferjs.com/ui/plugin/in/editor/config.html#point-iboxinputdata-iboxinputdata
> 
> 控制点是一个Box, 可以根据情况自定义，或增加子元素

再麻烦请教一下：还是没学会怎么用这个：这个chilren不知要怎么给值，我这样写，感觉好像没有生效。
![image](https://github.com/user-attachments/assets/4dd48b6c-d98b-4448-9575-6868adf0526f)
![image](https://github.com/user-attachments/assets/1c40661b-6590-4788-a492-0555a42a8940)

**Comment by leaferjs** [comment]
给JSON格式，具体可以看一下Box的这个例子， 把tag属性改成Image：

https://www.leaferjs.com/ui/reference/display/Box.html#%E5%88%9B%E5%BB%BA%E8%87%AA%E9%80%82%E5%BA%94%E8%83%8C%E6%99%AF%E7%9A%84%E6%96%87%E6%9C%AC

 另外，Box支持图片填充，走fill填充图片也可以（支持多个填充）

**Comment by 826327700** [comment]
> 给JSON格式，具体可以看一下Box的这个例子， 把tag属性改成Image：
> 
> https://www.leaferjs.com/ui/reference/display/Box.html#%E5%88%9B%E5%BB%BA%E8%87%AA%E9%80%82%E5%BA%94%E8%83%8C%E6%99%AF%E7%9A%84%E6%96%87%E6%9C%AC
> 
> 另外，Box支持图片填充，走fill填充图片也可以（支持多个填充）
好的，谢谢回复
