### ISSUE TITLE
leafer.remove与leafer.add连用bug

### ISSUE THREAD

**Issue by kooriookami** [leaferjs/ui#19]
有如下一段代码，其中`this.attribute`值可能是new Image或者null。发现两个问题，当draw执行时，图片尺寸会变化，不是原图大小。当重复执行draw时，会抛错。中途渲染会出现黑色方块。
版本：1.0.0-beta.6
```js
  draw() {
    this.leafer.remove(this.attribute);

    this.attribute = new Image({
      url: this.attributeSrc,
    });

    this.leafer.add(this.attribute);
  },
```
![image](https://github.com/leaferjs/ui/assets/38392315/6fbeea72-c31e-465f-97b1-8316bfcd4346)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复，等待发布新版本～
