### ISSUE TITLE
resizeWidth方法是哪个对象上的方法，容器元素好像显示的都是不存在

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#190]
版本 1.0.2

let group = new Group({
    children: app.value.tree.children
  }) 
  group.resizeWidth(300)

  let box = new Box({
    x: 0,
    y: 0,
    width: 500,
    height: 500
  })
  box.resizeWidth(300)

  let frame = new Frame({
    x: 0,
    y: 0,
    width: 500,
    height: 500
  })
  frame.resizeWidth(200)

![image](https://github.com/user-attachments/assets/1865194a-a3c2-441f-96ba-332cdecca13b)

**Comment by leaferjs** [comment]
估计你用的是老版本，这个方法是后来加的～

**Comment by leaferjs** [comment]
是不是刚更新到新版本，估计是TS提示没及时同步上， 退出一下编辑器再打开试试～

**Comment by leaferjs** [comment]
或者是你的 @leafer-ui/interface 的版本不对

**Comment by QmagicianEX** [comment]
> 是不是刚更新到新版本，估计是TS提示没及时同步上， 退出一下编辑器再打开试试～

嗯嗯，重新打开就可以了😅
