### ISSUE TITLE
小程序端短时间重新渲染报错

### ISSUE THREAD

**Issue by yifengyoujian** [leaferjs/ui#194]
版本号:  "@leafer-ui/miniapp": "^1.0.2",

提示错误: TypeError: Cannot read property 'requestAnimationFrame' of null 

具体实现: ![image](https://github.com/user-attachments/assets/4ea3be40-5c74-4e14-818e-63eee075a434)

描述: 依赖的harmonize会短时间变化多次, 偶现这个错误

**Comment by yifengyoujian** [comment]
![image](https://github.com/user-attachments/assets/fb822d22-87ab-4ccd-b18c-465a1727e6c5)

**Comment by yifengyoujian** [comment]
使用的Taro react版本。可能出错的原因是没有被taro进行编译requestAnimationFrame(e){return window.requestAnimationFrame(e)}。重写Platform.requestRender = function (render) {
  requestAnimationFrame(render);
};恢复正常

**Comment by leaferjs** [comment]
react版要注意开发环境 useEffect会执行两次的问题

 https://www.leaferjs.com/ui/guide/framework/react/

**Comment by yifengyoujian** [comment]
![image](https://github.com/user-attachments/assets/7620ffbf-9ac7-4379-8fe8-9fdab00aef1e)
引入重写解决

**Comment by parox2014** [comment]
> ![image](https://github.com/user-attachments/assets/7620ffbf-9ac7-4379-8fe8-9fdab00aef1e) 引入重写解决

哥们，我也遇到了这个问题
你重写时，那个requestAnimationFrame是哪里来的，小程序里没有这个全局的api啊

**Comment by yifengyoujian** [comment]
> > ![image](https://github.com/user-attachments/assets/7620ffbf-9ac7-4379-8fe8-9fdab00aef1e)导入重写解决方案
> 
> 兄弟们，我也遇到了这个问题 你重写的时候，那个requestAnimationFrame是哪里来的，小程序里没有这个通用的api啊

小程序更新了吧, 我看文档现在好像在Canvas里面
