### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by yifengyoujian** [leaferjs/ui#197]
渲染完毕后画布是还在不停进行渲染吗, 有没有暂停画布的办法

**Comment by yifengyoujian** [comment]
这边调用了stop方法, 发现内置的requestRender还在不停的进行打印 
![image](https://github.com/user-attachments/assets/ba7fd784-82bd-4c92-b6ae-b0bf2bf32b34)
![image](https://github.com/user-attachments/assets/d677703f-e67e-4973-9000-0ac4218dee08)

**Comment by leaferjs** [comment]
requestRender 方法是监听系统的渲染帧（会不断运行），和内部leafer的渲染是两回事，leafer是按需渲染的（有内容变化才会渲染）
