### ISSUE TITLE
给view属性赋值Dom元素，canvas里没有渲染内容

### ISSUE THREAD

**Issue by Chanyon** [leaferjs/ui#2]
`view: window`时有内容；
`view: div_dom`时没有内容；

![image](https://github.com/leaferjs/ui/assets/40350332/f7b0b1c0-2d04-465e-8d02-a3b91880c4e4)

**Comment by leaferjs** [comment]
div 需要添加到页面中才会显示，像下面这样时可以的，如果有特殊情况可附上可以完整代码，我们再调试下看～

![WX20230701-214337](https://github.com/leaferjs/ui/assets/83396016/08d620f2-b76b-478a-b6b6-ed4ec79dbde3)

**Comment by Chanyon** [comment]
> div 需要添加到页面中才会显示，像下面这样是可以的，如果有特殊情况可附上完整代码，我们再调试下看～
> 
> ![WX20230701-214337](https://user-images.githubusercontent.com/83396016/250279200-08d620f2-b76b-478a-b6b6-ed4ec79dbde3.png)

`完整代码link`https://github.com/Chanyon/van-ui-demo/blob/b6a566a0504c4b8c9a056f30cc340559147aa136/src/views/profile/index.ts#L7C30-L7C30

**Comment by leaferjs** [comment]
innerHTML之后，已经不是之前的Canvas实例了，所以不会显示。建议给div设置一个id, 监听路由页面创建完成之后，再通过id来实例化Leafer。

![image](https://github.com/leaferjs/ui/assets/83396016/522160ba-6a23-4b54-8a01-54770c84fabf)

**Comment by Chanyon** [comment]
> innerHTML之后，已经不是之前的Canvas实例了，所以不会显示。建议给div设置一个id, 监听路由页面创建完成之后，再通过id来实例化Leafer。
> 
> ![image](https://user-images.githubusercontent.com/83396016/250312350-522160ba-6a23-4b54-8a01-54770c84fabf.png)

Thank you!
