### ISSUE TITLE
new Text字符串为空字符串或空格报错

### ISSUE THREAD

**Issue by kooriookami** [leaferjs/ui#20]
```js
  const text = new Text({
    text: ' ',
    fill: 'black',
  });

  this.leafer.add(text);
```
当text为空字符串或者空格报错
![image](https://github.com/leaferjs/ui/assets/38392315/023bb294-9732-429f-ad0b-68dc6a8e8296)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by chengchongzhen** [comment]
感觉是少了个判断, 本想蹭个pr的

https://github.com/leaferjs/ui/blob/58c58003272bedf87fd5e6bbc99837a88a06fd15/packages/text/src/TextRows.ts#L106C45-L106C45

![image](https://github.com/leaferjs/ui/assets/52627267/f1eaa32d-01f8-4cca-8825-58670d9381e6)

**Comment by chengchongzhen** [comment]
rows.length > 0 && rows[rows.length - 1].paraEnd = true

**Comment by leaferjs** [comment]
收到
