### ISSUE TITLE
Rect大小被填充的图片撑开

### ISSUE THREAD

**Issue by leidao** [leaferjs/ui#201]
<img width="486" alt="image" src="https://github.com/user-attachments/assets/5d8f96fe-b826-4c19-ba75-ae03ed7e196b">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/0452e6c4-4bef-4580-8dc3-1ada850ee8ac">

如图，我有一个rect，使用[图案填充](https://www.leaferjs.com/ui/reference/property/paint/image.html)后直接被图片撑开，大小改变了，我希望能不改变大小，请问该怎么做

**Comment by leaferjs** [comment]
给Rect设置一个固定宽高就行。

截图中是一个自动宽高的Rect(默认给了100*100，会随背景图片的实现大小自适应）。
