### ISSUE TITLE
导出的时候会显示编辑框

### ISSUE THREAD

**Issue by code-small-white** [leaferjs/ui#211]
<img width="219" alt="image" src="https://github.com/user-attachments/assets/d1f73ab9-e552-4b6f-a665-81acec7310b9">

不想要这个编辑框,如果在导出的时候隐藏,导出完再显示,会闪烁一下,体验不好,有没有什么好的办法

**Comment by leaferjs** [comment]
单独导出内容就行：app.tree.export()

**Comment by code-small-white** [comment]
> 单独导出内容就行：app.tree.export()

如果有天空层呢

**Comment by code-small-white** [comment]
试了下 而且导出tree的话就只有里面的内容了和app.export导出的效果不一致

**Comment by code-small-white** [comment]
```js
 app.tree.export('png', {screenshot: true })
```
`screenshot`设置为true就正常了
