### ISSUE TITLE
在使用剪贴遮罩时候遇到了点问题。

### ISSUE THREAD

**Issue by PeerQuan666** [leaferjs/ui#212]
在css样式中设置了蒙版并且mix-blend-mode:'screen' 会使黑色部分变透明，

![image](https://github.com/user-attachments/assets/0c04fb3f-c0ac-40ce-a909-19967e874570)

在使用剪贴遮罩并设置了blendMode:'screen'却没有相同的效果，请问该如何实现。

```

const leafer = new Leafer({ view: window })
const group = new Group({ x: 100, y: 100, draggable: true })
const image = new Image({
    width: 100,
    height: 100,
    url: '/public/test4.png',
    blendMode:'screen'
})

const mask = new Image({
    width: 100,
    height: 100,
    url: '/public/test5.png',
    mask :'clipping'
})

group.add(mask)
group.add(image)

leafer.add(group)
```

**Comment by leaferjs** [comment]
目前还不支持黑白的蒙版，需要将黑白蒙版通过canvas像素操作转换为一个透明蒙版，再导出给图片元素：

每个像素的颜色由r,g,b,a四个色彩值构成，把r,g,b中的任意一个值赋值给a,   即可产生一个透明蒙版
