### ISSUE TITLE
1.0.3版本有多余的console没删除,在编辑时会频繁触发

### ISSUE THREAD

**Issue by RanMaoting** [leaferjs/ui#213]
![image](https://github.com/user-attachments/assets/b6343539-f2d7-44ad-960e-9de6876d1de2)
![image](https://github.com/user-attachments/assets/f26c4ec8-5704-4a6a-941b-198c7a1d202e)

**Comment by leaferjs** [comment]
啊。。。,  我看了下，源码删除了，编译的代码里面有，我晚上补发一个版本，感谢反馈～

**Comment by leaferjs** [comment]
已经发布新版本了～
