### ISSUE TITLE
Arrow 设置路径方式绘制，在编辑状态下，resize 异常

### ISSUE THREAD

**Issue by tiny-dust** [leaferjs/ui#214]
代码：[![Cloud Studio Template](https://cs-res.codehub.cn/common/assets/icon-badge.svg)](https://cloudstudio.net/a/21290378676813825?channel=share&sharetype=Markdown)
效果：
![20240924171415](https://github.com/user-attachments/assets/27f976f3-9b00-4ff8-8cf0-7d318ecf74e9)

**Comment by leaferjs** [comment]
应用不存在，是不是删除了

**Comment by tiny-dust** [comment]
> 应用不存在，是不是删除了

应该是权限问题，稍等我去看一下

**Comment by tiny-dust** [comment]
> 应用不存在，是不是删除了

好了

**Comment by leaferjs** [comment]
更新到最新版本，就能解决，之前确实存在这个问题～

**Comment by tiny-dust** [comment]
> 镜像的时候发现确实有问题，已修复，等待下个版本发布～

辛苦大佬了
