### ISSUE TITLE
cloudstudio演示

### ISSUE THREAD

**Issue by amourlemon** [leaferjs/ui#215]
使用cloudstudio演示动画无效

**Comment by leaferjs** [comment]
发现问题了，是版本更新的问题～，下午会同步一下版本过去

**Comment by leaferjs** [comment]
现在可以去用了～

**Comment by amourlemon** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月26日(星期四) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leaferjs/ui] cloudstudio演示 (Issue #215)














 
现在可以去用了～
