### ISSUE TITLE
wheel.zoomMode:true不生效

### ISSUE THREAD

**Issue by akssmaw** [leaferjs/ui#22]
const leafer = new Leafer({
			view: window,
			wheel: {
				zoomMode: true,
			},
		}) 不生效 需要阻止系统滚轮吗？

**Comment by leaferjs** [comment]
能贴完整代码吗，我这边本地测试是可以生效的，滚动滚轮就可以缩放画面。

**Comment by akssmaw** [comment]
<!DOCTYPE html>
<html>
	<head>
		<title>Million Rects | Leafer UI</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width,initial-scale=1" />
		<script src="https://unpkg.com/leafer-ui"></script>
	</head>

	<body>



	</body>

	<script>
		var Leafer = LeaferUI.Leafer
		var Group = LeaferUI.Group
		var Rect = LeaferUI.Rect
		var Debug = LeaferUI.Debug
		var ZoomEvent = LeaferUI.ZoomEvent
		var PointerEvent  = LeaferUI.PointerEvent 
		const leafer = new Leafer({
			view: window,
			wheel: {
				zoomMode: true,
			},
		})
		let size = 100

		for (let i = 0; i < size; i++) {
			let row = "";
			for (let j = 0; j < size; j++) {
				const rect = new Rect()

				rect.x = j * 5.5
				rect.y = i * 5.5
				rect.height = 5
				rect.width = 5
				rect.fill = "red"
				rect.draggable = true
				rect.on(PointerEvent.TAP, (item) => { 
				    rect.fill = 'green'
				})
				leafer.add(rect)
			}
			console.log(row);
		}
	</script>
</html>这是我全部代码了

**Comment by leaferjs** [comment]
我这边测试还是可以用，滚动鼠标就能缩放。你的用浏览器、系统版本是？或者指定这个版本试试   https://unpkg.com/leafer-ui@1.0.0-beta.6/dist/global.js

**Comment by akssmaw** [comment]
我使用的金丝雀的google 刚才用同事的google浏览器也测试了  也是不行的

**Comment by akssmaw** [comment]
![7996d84200fbb8f20a7c077f3a9929bf](https://github.com/leaferjs/ui/assets/48310423/db9bc1c3-581a-4349-be20-5981bdd01bf5)

**Comment by leaferjs** [comment]
刚在windows电脑上试了下，确实存在这个问题，谢谢反馈， 今天修复下

**Comment by akssmaw** [comment]
好滴

**Comment by leaferjs** [comment]
已修复，等待发布新版本～

**Comment by leaferjs** [comment]
新版本已发布～

**Comment by firimar** [comment]
Chrome   121.0.6167.85（正式版本） (arm64) 
mac上用上面的代码wheel.zoomMode:true 也不生效

**Comment by firimar** [comment]
> 新版本已发布～

Chrome 121.0.6167.85（正式版本） (arm64)
mac上用上面akssmaw提供的代码wheel.zoomMode:true 不生效
