### ISSUE TITLE
鼠标 移动到 对象上时，边框显示有问题，有的显示，有的不显示，有的显示分部，

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/ui#221]
鼠标 移动到 对象上时，边框显示有问题，有的显示，有的不显示，有的显示分部

![动画](https://github.com/user-attachments/assets/5837a025-1fca-430a-9e93-8f131913193a)

**Comment by leaferjs** [comment]
你是不是没关闭sky层的局部渲染？
![image](https://github.com/user-attachments/assets/7629acfd-09a7-4298-be99-15d6d8571530)

**Comment by 3400442579** [comment]
_lapp = new App({
        view: id,
        tree: { type: 'draw' },
        sky: { type: 'draw' },
        editor: {
            //around: 'center',
            point: { cornerRadius: 0 },
            middlePoint: {},
            rotatePoint: { width: 10, height: 10 },
            rect: { dashPattern: [3, 2] }
        },
        move: { scroll: 'limit' }
    });

**Comment by 3400442579** [comment]
import {
    ScrollBar,
    App,
    Rect,
    Group,
    Canvas as LCanvas,
    Box,
    Image as LImage,
    Path as LPath,
    Text as LText,
    UI,
    Platform,
    PointerEvent,
    DragEvent,
    EditorEvent,
    PropertyEvent,
    dataType
} from 'leafer-editor';

**Comment by 3400442579** [comment]
![image](https://github.com/user-attachments/assets/cb38c59e-bea8-4f75-a342-c7bb429d32bd)
这种只有一部的

**Comment by leaferjs** [comment]
少加 usePartRender 参数了，我上一张截图已经猜到了：

sky: { type: 'draw', usePartRender: false }

**Comment by leaferjs** [comment]
官网示例的sky层都加了这个参数
