### ISSUE TITLE
当Image的url修改后，图片尺寸没有自动调节

### ISSUE THREAD

**Issue by kooriookami** [leaferjs/ui#26]
图片有两个问题：
1. new Image()一个图片，不设置宽高，去修改url，得到的图片尺寸还是上一张图的大小
2. 当leafer设置scaleX与scaleY时，进行画布缩放，图片会产生锯齿，应该是没有重新绘制导致的

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复～
