### ISSUE TITLE
如何删除leafer的children中的某一项元素

### ISSUE THREAD

**Issue by register2019** [leaferjs/ui#29]
<img width="1149" alt="iShot_2023-07-30_15 23 00" src="https://github.com/leaferjs/ui/assets/51252517/64383d4c-6b6e-4b57-bdc4-2f8aebaa5e15">

**Comment by leaferjs** [comment]
leafer.remove(child)  

或者

const child = leafer.children.indexOf(6)
leafer.remove(child)
