### ISSUE TITLE
leaferjs可以设置shape的中心参考点吗

### ISSUE THREAD

**Issue by weigram** [leaferjs/ui#3]
耗时一下午做了一个echarts的demo，还有动画。
https://codepen.io/kooro/pen/poQPqwq
在设置圆圈缩放时，最开始用的是修改宽高，缩放后，左上角点位置不变，导致圆圈中心点偏移，后来用scale，是围绕中心缩放的。有没有类似fabricjs那样设置originX的，或者leaferjs修改宽高怎么实现类似中心点不变。
非常棒的框架，我想好好学习一下，但是基础不是很好，有群可以沟通交流吗。

**Comment by leaferjs** [comment]
看了一下你做的例子，非常棒[强]

**Comment by mizhousoft** [comment]
看了下demo代码，应用到实际场景中感觉还是有点复杂了，如果能封装成业务场景就更好了，比如图表等
应用在小程序上还是挺不错的，代码量小是很大优势

**Comment by leaferjs** [comment]
> 看了下demo代码，应用到实际场景中感觉还是有点复杂了，如果能封装成业务场景就更好了，比如图表等 应用在小程序上还是挺不错的，代码量小是很大优势

非常好的反馈，我们最近也在准备推出小程序版

**Comment by leaferjs** [comment]
@weigram  新版本已经具备围绕中心点旋转的功能了，还有动画事件支持 https://leaferjs.com/ui/guide/animate/
