### ISSUE TITLE
小程序计划支持预期日期

### ISSUE THREAD

**Issue by 2321605193** [leaferjs/ui#30]
能告知下小程序支持预期日期么

**Comment by leaferjs** [comment]
预计本周发布～

**Comment by 2321605193** [comment]
好的，谢谢回复，能问下稍微具体点日期吗？因为项目时间比较紧急了，看了leafer项目觉得挺有意思也挺符合需求得，但赶不上时间得话可能得考虑SpriteJS 了，虽然比较难用。。。

**Comment by leaferjs** [comment]
预计周四晚或周五发版～

**Comment by leaferjs** [comment]
看你的项目紧急程度，也可以先用web版实现主体功能，到时可以平替过去， 小程序目前只支持传canvas的id作为view， 导出的图片支持直接放入相册

**Comment by leaferjs** [comment]
小程序版已初步开发完成，还有些问题需要解决，等下一版再上线～
