### ISSUE TITLE
Line如何设置绘制起始点？

### ISSUE THREAD

**Issue by penguin0731** [leaferjs/ui#33]
文档中似乎只有设置目标点的坐标，没有起始点的坐标，起始点默认都是从原点开始吗？

**Comment by leaferjs** [comment]
line可以设置x, y坐标作为起点（所以元素都支持x,y, scalex...基础属性)， toPoint是相对x, y坐标的结束点

**Comment by penguin0731** [comment]
> line可以设置x, y坐标作为起点（所有元素都支持x,y, scaleX...等基础属性)， toPoint是相对x, y坐标的结束点

「toPoint是相对x, y坐标的结束点」，这个很关键呀，我看了下文档没有这个描述，以为toPoint是相对画布原点的，结果在画网格线的时候发现线的结束点都偏移了。建议加上这个描述。

**Comment by leaferjs** [comment]
谢谢反馈，我们这就加上～
