### ISSUE TITLE
拖拽源对象的属性能否增加鼠标相对拖拽元素原点的距离，类似Dom中的offsetX、offsetY？

### ISSUE THREAD

**Issue by penguin0731** [leaferjs/ui#34]
目前正在实现一个拖拽吸附的功能，但是由于无法获取到的拖拽对象的原点实际的移动坐标，导致实现效果不理想。

当鼠标拖拽元素底部时的效果：
![test1](https://github.com/leaferjs/ui/assets/39406604/53ef0b0a-d74c-4ef9-b516-f34f25628b14)

只有鼠标拖拽元素原点时，效果才比较理想：
![test2](https://github.com/leaferjs/ui/assets/39406604/a669e0c6-1285-4871-b1a4-477eb02a1662)

所以是否能够像Dom的事件源对象那样给出鼠标相对元素左上角的距离？

**Comment by leaferjs** [comment]
后面计划会在事件中增加相对元素的inner坐标，以及相对父节点的local坐标，目前可以通过坐标转换实现。

转换为相对元素的坐标：
const point = { x: event.x, y: event.y } // world
rect.worldToInner(point)
console.log(point)  // inner

转换为相对元素的移动距离：
const move = { x: event.moveX, y: event.moveY } // world
rect.worldToInner(move, null, true)
console.log(move)  // inner

坐标转换详情请看： https://leaferjs.com/ui/guide/basic/coordinate.html

也可以加交流群沟通哈～
