### ISSUE TITLE
目前有增加元素控制器的计划吗？

### ISSUE THREAD

**Issue by overdev-l** [leaferjs/ui#36]

**Comment by leaferjs** [comment]
最近会开发基础的元素缩放、旋转控制器（编辑器），可以关注一下我们的开发看板：

https://github.com/leaferjs/ui/projects

**Comment by leaferjs** [comment]
已开发完成，等待新版本发布～

**Comment by leaferjs** [comment]
图形编辑器已上线：https://leaferjs.com/ui/guide/plugin/editor.html
