### ISSUE TITLE
请问为啥这个库与其他库对比的性能如此强？能在官网说明一下么？或者有技术交流群么（想学习一下）

### ISSUE THREAD

**Issue by chris1299** [leaferjs/ui#4]

**Comment by leaferjs** [comment]
1. 是无数个小细节做到极致，累加在一起的结果，我们后面会写一篇文章详细说明一下，最近我们还有很多开发工作要做。
2. 刚创建的微信技术交流群， 扫码即可加入。
![wechat-group](https://github.com/leaferjs/ui/assets/83396016/f1f40c41-6c1c-49a4-bdd2-75ef7c8992e7)

**Comment by chris1299** [comment]
谢谢，期待

**Comment by Qiu-Jun** [comment]
> 谢谢，期待

你好，我想问下，为什么要挂在window对象下

**Comment by Qiu-Jun** [comment]
>  有部分用户是直接<script>标签引用库的，global.ts和index.ts我们准备合并，这块还有变动，如果是import导入的先别用LeaferUI全局变量。
> 
> 
> 
> 

了解

**Comment by yh4922** [comment]
二维码过期了

> 1. 是无数个小细节做到极致，累加在一起的结果，我们后面会写一篇文章详细说明一下，最近我们还有很多开发工作要做。
> 2. 刚创建的微信技术交流群， 扫码即可加入。
>    ![wechat-group](https://user-images.githubusercontent.com/83396016/250797414-f1f40c41-6c1c-49a4-bdd2-75ef7c8992e7.jpg)

**Comment by leaferjs** [comment]
谢谢反馈，群二维码已更新！

![wechat-group-0710](https://github.com/leaferjs/ui/assets/83396016/454e6911-eb74-49b2-849e-adc3507e68f9)

**Comment by dearDreamWeb** [comment]
功能单一的原因，宣传渲染100万个rect说的多少有些标题党的，把fabric的每个图像创建是有控制器，可以进行缩放，图层的之间是有层级的，这个这些计算都是没有的，计算量相对于fabric是太小了，能渲染的不快吗
