### ISSUE TITLE
属性编辑，除了支持填充/描边外，请问支持改色和圆角吗？

### ISSUE THREAD

**Issue by mingwong1278** [leaferjs/ui#40]

**Comment by leaferjs** [comment]
目前只有矩形支持圆角， 后面其他图形和路径也会增加圆角支持～
改色是指改变颜色？

所有的图形元素都会继承这些属性：
https://leaferjs.com/ui/guide/display/UI.html

**Comment by leaferjs** [comment]
暂时还不支持，后面会通过插件提供此功能
