### ISSUE TITLE
绘制line异常

### ISSUE THREAD

**Issue by tiny-dust** [leaferjs/ui#45]
![image](https://github.com/leaferjs/ui/assets/49502875/b9b0d726-f2a7-4647-91e7-1b89ec6c0f0e)
这是代码和坐标点

正常应该是竖线 但是实际的结果是这样的
<img width="555" alt="image" src="https://github.com/leaferjs/ui/assets/49502875/5ae9c1b0-dc51-44a2-8a18-78b13699644d">

另外，交流群的过期了，有新的吗

**Comment by leaferjs** [comment]
谢谢反馈～， 交流群二维码已更新


![wechat-group](https://github.com/leaferjs/ui/assets/83396016/cb65bc2d-c761-4f29-a6ee-e29f5a21dbf7)

**Comment by leaferjs** [comment]
toPoint是相对起始坐标的点：toPoint = endPos - startPos

![image](https://github.com/leaferjs/ui/assets/83396016/69a2cd14-0c22-4cb5-86d1-3d1cdac485e4)
