### ISSUE TITLE
画布位置偏移导致画布中元素实际拖拽区域发生变化

### ISSUE THREAD

**Issue by penguin0731** [leaferjs/ui#46]
![image](https://github.com/leaferjs/ui/assets/39406604/13262003-6774-4c48-a54a-632334a29c0a)

demo地址：https://codepen.io/penguin0731/pen/PoXYWaM

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复，等待新版本发布～
