### ISSUE TITLE
[小程序 uniapp环境] 无法挂载到canvas如何解决

### ISSUE THREAD

**Issue by 2321605193** [leaferjs/ui#47]
项目环境：uniapp + vue3 +script-setup + vite

现象：等canvas渲染完成后，在初始化leafer，提示无法找到canvas，但实际是canvas已经渲染

排查：eventer需要传入this才行，

问题：传入vue3的proxy 还是报错

规避：使用uniapp 中的 getCurrentPages，且必须在pages的第一个页面下，无法在子组件中使用

```
const pages = getCurrentPages();

leaferImageLayer.value = new Leafer({
            view: canvasId,
            width: clientWidth.value,
            height: clientHeight.value,
            eventer: pages[pages.length - 1],
         
        });
```

期望：看下后续是否能够兼容uniapp vue3

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by yy8z7** [comment]
期待啊 什么时候更新

**Comment by yy8z7** [comment]
作者哥哥：期望后续是否能够兼容uniapp vue3  啊

**Comment by leaferjs** [comment]
正在适配中

**Comment by leaferjs** [comment]
> 作者哥哥：期望后续是否能够兼容uniapp vue3 啊

正在适配中

**Comment by yy8z7** [comment]
那就太好了 有大概上线的时间嘛




Role&nbsp;Reversal
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leaferjs/ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 下午2:40
***@***.***&gt;;
抄送:&nbsp;"Role ***@***.******@***.***&gt;;
主题:&nbsp;Re: [leaferjs/ui] [小程序 uniapp环境] 无法挂载到canvas如何解决 (Issue #47)





  
作者哥哥：期望后续是否能够兼容uniapp vue3 啊
  
正在适配中

**Comment by leaferjs** [comment]
估计最近一两周

**Comment by yy8z7** [comment]
那就太好了 应该浅浅的打赏一下




Role&nbsp;Reversal
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leaferjs/ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 下午4:56
***@***.***&gt;;
抄送:&nbsp;"Role ***@***.******@***.***&gt;;
主题:&nbsp;Re: [leaferjs/ui] [小程序 uniapp环境] 无法挂载到canvas如何解决 (Issue #47)





 
估计最近一两周

**Comment by leaferjs** [comment]
新版本已发布～
