### ISSUE TITLE
[小程序] leafer中创建Ellipse，并实时更新其xy坐标时，在小程序真机上无法缩放和拖拽了

### ISSUE THREAD

**Issue by 2321605193** [leaferjs/ui#48]
现象： leafer中创建Ellipse，并实时更新其xy坐标时，在小程序真机上无法缩放和拖拽了

使用Rect可以

**Comment by 2321605193** [comment]
rect 配置了cornerRadius也不可以了

**Comment by leaferjs** [comment]
谢谢反馈，经测试在动画事件中实时修改坐标，然后缩放拖拽是没问题的～，还需要进一步确定具体复现步骤。

**Comment by 2321605193** [comment]
最终解决：使用Pen画圆，再更改Pen的实时位置，验证是可以缩放和移动的
