### ISSUE TITLE
[建议] 图形坐标配置建议

### ISSUE THREAD

**Issue by 2321605193** [leaferjs/ui#49]
当前图形配置坐标的位置都是其左上角，很多时候需要计算图形展示的真实位置

例如
圆形 配置中心点坐标及半径即可
矩形 配置其四个点坐标即可
line 也可以是线上每个点的坐标即可，这样不管是直线还是曲线都极易配置
多边形 其实也是line组成的闭合区域，是line的配置加个是否闭合配置即可，如果有多变型的合并和分割等需求，也是一些点的计算，比较方便，现有多边形的xy配置比较难找准其真实需要展示的位置

**Comment by leaferjs** [comment]
收到，谢谢反馈～， 最近计划会新增一个通过points描述折线、平滑曲线、多边形的图形类。

Pen提供了从中心点画圆的方法：（针对当前图形配置坐标的位置都是其左上角，这个是为了方便图形编辑的场景）
https://leaferjs.com/ui/guide/display/Pen.html

**Comment by leaferjs** [comment]
直线和多边形和新增了points 坐标组属性，并且支持变为平滑曲线， 等待新版本发布～

**Comment by leaferjs** [comment]
并且增加了从中心点开始绘制任何图形的功能

**Comment by leaferjs** [comment]
新增 points 绘制属性 （[Line](https://leaferjs.com/ui/guide/display/Line.html)、[Polygon](https://leaferjs.com/ui/guide/display/Polygon.html)）, 并支持转为平滑曲线，已上线～
