### ISSUE TITLE
UI.one 创建图形报错

### ISSUE THREAD

**Issue by Alessandro-Pang** [leaferjs/ui#5]
通过 UI.one 创建图形报错，代码如下：

<img width="200" alt="image" src="https://github.com/leaferjs/ui/assets/42641570/d48284be-a39e-41ae-b7db-ceb556705407">

报错信息如下：
<img width="721" alt="image" src="https://github.com/leaferjs/ui/assets/42641570/fe94bf82-1f77-4e2b-bee1-bafc421cee73">

Leafer UI版本: 1.0.0-beta.3

可复现地址：[https://codesandbox.io/p/sandbox/dark-cherry-5mp2sh](https://codesandbox.io/p/sandbox/dark-cherry-5mp2sh)

**Comment by leaferjs** [comment]
谢谢反馈，问题已修复，需要更新下版本

**Comment by Alessandro-Pang** [comment]
ok，已测试无问题
