### ISSUE TITLE
非微信的小程序如何兼容？

### ISSUE THREAD

**Issue by liangei** [leaferjs/ui#50]
大佬，如何兼容其它小程序呢？我看好像只支持微信小程序，其它小程序大多是非canvas 2d，也不支持创建离屏的API。
能否像node环境一样使用useCanvas这个方法把canvas传入，以达到兼容更多支持canvas的小程序？而且非canvas 2d 的context 需要使用context.draw()这个方法才能把元素渲染到画板。能否在底层就支持一下这个方法？

我希望是有这么一个方法,设置平台前缀，加载图片，创建canvas，然后leaferjs底层ctx多判断ctx是否存在draw()方法，如果有就执行。

```js
setPlatformAPI({
     platform: wx,
     createCanvas，
     loadImage，
})
```

**Comment by leaferjs** [comment]
等小程序版本稳定了，后面计划会逐步支持其他的小程序（前期先支持有canvas2D接口的，非canvas2D匹配兼容性的工作量比较大，我们到时看大家的需求情况），自动通过全局变量就能检测匹配到不同平台。
