### ISSUE TITLE
[建议]提供esm模块打包文件

### ISSUE THREAD

**Issue by FliPPeDround** [leaferjs/ui#53]
你好，请问leafer-ui的打包文件只提供了cjs吗？
在仓库中没有找到找到关于打包和发布的脚本
我在使用最新版本的vitepress只支持esm模块了

**Comment by leaferjs** [comment]
你好，我们默认提供的是esm模块的打包文件， vitepress使用了服务端渲染，需要动态引入涉及leafer-ui的相关代码才能运行。
> 具体原因可以看这里：https://leaferjs.com/ui/problem/


可以采用这种方式引入：

async mounted() {
    const  { Leafer } = await import('leafer-ui')
    ...
}




运行、打包的脚本，近期计划会开始提供。

**Comment by leaferjs** [comment]
晚点我也升级下最新版的vitepress试试哈，如有问题可以继续反馈～

**Comment by FliPPeDround** [comment]
好的，谢谢，我试试
