### ISSUE TITLE
Functionality similar to Konva.Transformer()

### ISSUE THREAD

**Issue by viccsjain** [leaferjs/ui#56]
In KonvaJS, when we use Konva.Transformer(), we can select a shape and a selection rectangle will be created on top of that.
Using which we can rotate the shape, strectch the shape etc. We can perform transformation on that shape. 
Do we have similar functionality available in leaferjs ?

Ref: https://konvajs.org/docs/select_and_transform/Transform_Events.html

**Comment by leaferjs** [comment]
This feature is not yet available, but it is already in our recent development plans.

https://github.com/users/leaferjs/projects/2

**Comment by viccsjain** [comment]
Thanks for the update. Any tentative timeline for this feature ?

**Comment by leaferjs** [comment]
Expect next week.

**Comment by leaferjs** [comment]
It has been developed and will be released after testing and refining.

**Comment by viccsjain** [comment]
This is great to hear, Eagerly waiting to try it out.

**Comment by leaferjs** [comment]
Published： https://leaferjs.com/ui/guide/plugin/editor.html
