### ISSUE TITLE
Text组件设置letterSpacing属性value为负数且元素数量>=2时，向左拖动元素出现阴影

### ISSUE THREAD

**Issue by LvHuaiSheng** [leaferjs/ui#57]
- 问题描述
在Chrome中设置letterSpacing中的value为负数且元素数量>=2时，向左拖动元素出现阴影
- 运行环境
Chrome 版本 116.0.5845.180（正式版本） （64 位）
- 复现Demo
[https://codepen.io/huaiseng/pen/VwqPqYV](https://codepen.io/huaiseng/pen/VwqPqYV)
- 问题截图
![图片](https://github.com/leaferjs/ui/assets/35132878/716f22bb-3253-4c14-8e13-30bf2b1a0e58)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复～
