### ISSUE TITLE
How to fill patterns in a shape and rotate a shape from different origin point

### ISSUE THREAD

**Issue by vikkyjain2013** [leaferjs/ui#58]
Hi Team,

Thanks for this wonderful library and your performance results are unbelievable. I have started exploring this library to check if it fits into some of my project requirements. I am currently looking for two answers here:
1. How can i rotate a object through a point which is not inside that shape ? Assume i have a shape drawn at (10,10) and (200,100). Now i want to rotate this shape assuming its center point is located at (15,5). This point is outside of this shape. How can we achieve that ?
2. I want to fill any kind of shapes with various patterns like horizontal lines, vertical lines, diagonal lines. When user zoom-into those shapes, gap between pattern should remain constant. It should not increase or decrease. Intensity of stroke should also be consistent. If require, i can provide a gif for this as well. 

Thanks,
Vj

**Comment by vikkyjain2013** [comment]
![recordings](https://github.com/leaferjs/ui/assets/131866319/5b49cef1-86be-4f7a-bcb2-00dd45fb891a)

**Comment by leaferjs** [comment]
Hi, Thank you for your feedback.

1. Use rotateOf(origin, rotation)：https://leaferjs.com/ui/guide/property/layout.html#%E5%85%B3%E9%94%AE%E6%96%B9%E6%B3%95
2. This feature is not supported yet, but we can add it later.

In the new release, we will add the fromCenter property, which makes it easier to draw, rotate, and scale around an origin.
The new version is released tonight or tomorrow.
