### ISSUE TITLE
打包工具热更新引起的 LeaferTypeCreator 重新注册问题

### ISSUE THREAD

**Issue by Alessandro-Pang** [leaferjs/ui#6]
现代打包工具（如： webpack / vite ）检测到代码更新后会重新编译，此时 leafer 的类型注册机制就会产生误判:

注册代码：

<img width="452" alt="image" src="https://github.com/leaferjs/ui/assets/42641570/05def185-a83b-48d5-b9b1-25f17505c9c1">

注册机源码：

<img width="438" alt="image" src="https://github.com/leaferjs/ui/assets/42641570/5f1ee36a-10be-4cbf-b3fd-de3ef02ec351">

报错信息如下：
<img width="704" alt="image" src="https://github.com/leaferjs/ui/assets/42641570/70569b6f-f014-442f-8c8f-de30b4d2bcc4">

Leafer UI版本: 1.0.0-beta.4

可复现地址：https://codesandbox.io/p/sandbox/funny-ully-t3r8pf

复现步骤：代码中随便编辑点什么，保存后页面重新编译，控制台此时会报出异常

**Comment by leaferjs** [comment]
谢谢反馈，今天会再发布一个版本，到时一起更新。

**Comment by leaferjs** [comment]
@Alessandro-Pang  问题已修复，需要更新下版本
