### ISSUE TITLE
希望鼠标样式可以自由开关，目前太影响自定义的一些鼠标样式了 ！

### ISSUE THREAD

**Issue by OldGong** [leaferjs/ui#60]
希望鼠标样式可以自由开关，目前太影响自定义的一些鼠标样式了 ！

**Comment by leaferjs** [comment]
收到反馈～，可以先试试自定义覆盖系统光标， 抓手是grab与grabbing。

https://leaferjs.com/ui/guide/property/cursor.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%89%E6%A0%87

系统默认光标列表：https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor

或者可以列举下具体场景，我们看看是不是目前的cursor可以进一步完善

**Comment by OldGong** [comment]
这个明白， 但想在恰当的时机，显示不同鼠标样式的时候，很不方便；
目前只有通过这样覆盖方法来解决问题
leafer.canvas.setCursor = () => {};

**Comment by leaferjs** [comment]
OK， 好嘞，那我们加个开关选项

**Comment by leaferjs** [comment]
新增cursor配置： new Leafer({view: 'id',  cursor: {stop: true}})，同时更新了cursor在不同层级下的显示逻辑，保持和html一致， 等待发版~

**Comment by leaferjs** [comment]
已上线～
