### ISSUE TITLE
不规则图片描边

### ISSUE THREAD

**Issue by ieleg** [leaferjs/ui#61]
添加对不规则图片（带透明的png）描边的支持，而不是矩形描边
实际渲染：
![image](https://github.com/leaferjs/ui/assets/52823905/fb13cf87-9483-449e-a0f5-ee4c49e8c55c)
期望渲染：
![image](https://github.com/leaferjs/ui/assets/52823905/5039b04f-aec2-4226-9b5c-f2054482ab8e)

**Comment by leaferjs** [comment]
收到，目前可以通过投影实现你说的这个效果，我们先研究下可行性～

**Comment by ieleg** [comment]
模糊程度为1的投影只能控制一个方向上的吧（x,y）

> 收到，目前可以通过投影实现你说的这个效果，我们先研究下可行性～

**Comment by leaferjs** [comment]
可以通过阴影的spread属性向四周扩散

**Comment by ieleg** [comment]
> 可以通过阴影的spread属性向四周扩散

是的，对于矩形的图片可以，但是不规则图片有这个问题
[https://github.com/leaferjs/ui/issues/62](url)

**Comment by leaferjs** [comment]
ok, 下次发版我们修复下这个问题

**Comment by leaferjs** [comment]
新版本已发布，发现spread貌似也不太适合解决这个问题，目前看只能通过多个阴影blur，可以大概模拟这个效果～
