### ISSUE TITLE
不规则图片投影

### ISSUE THREAD

**Issue by ieleg** [leaferjs/ui#62]
shadow: {
     color: 'black',
      x: 10,
      y: 10,
      blur: 1,
      // spread: 10,
    }

实际渲染：
![image](https://github.com/leaferjs/ui/assets/52823905/ffc4c206-c02a-461e-8252-4f09595d7c68)

期望渲染：
![image](https://github.com/leaferjs/ui/assets/52823905/a9feee3d-494b-4713-a205-6c14842afad6)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by ieleg** [comment]
> 收到，谢谢反馈～

内阴影有相同的问题。
![image](https://github.com/leaferjs/ui/assets/52823905/9a09ad4c-1d83-401a-95c8-92556bdbfe4a)
这是我的解决方法
[https://jsfiddle.net/ieleg/gjrpvadL/](https://jsfiddle.net/ieleg/gjrpvadL/)

**Comment by leaferjs** [comment]
已修复，等待新版本发布～

**Comment by leaferjs** [comment]
已发布～
