### ISSUE TITLE
元素遮盖的渲染

### ISSUE THREAD

**Issue by ieleg** [leaferjs/ui#63]
当一个元素为遮盖时是否支持它本身也能渲染，或者还有其他方式能实现ps的剪切图层效果？
在ps中蓝色的圆当作展示的范围，但是也渲染了，猫粮图层是剪切图层。
![image](https://github.com/leaferjs/ui/assets/52823905/55f0a693-333d-431b-924e-3c5cbea5859a)
本地解析的结果：
![image](https://github.com/leaferjs/ui/assets/52823905/67b414e7-7127-4520-acbb-03ab6761812e)

**Comment by leaferjs** [comment]
在遮罩底部（同一个Group内）放置一个和遮罩一样的正常图形即可～

我先记录下，后续可以增加一个是否渲染遮罩本身的选项。

**Comment by leaferjs** [comment]
已支持， 请查看maskType属性
