### ISSUE TITLE
多边形圆角cornerRadius较大时表现出奇怪的形状或者毛刺

### ISSUE THREAD

**Issue by ieleg** [leaferjs/ui#66]
[https://jsfiddle.net/ieleg/6etmk357/](https://jsfiddle.net/ieleg/6etmk357/)

![image](https://github.com/leaferjs/ui/assets/52823905/25154ad0-c858-4082-b155-df581edc2166)
![image](https://github.com/leaferjs/ui/assets/52823905/e327ee47-444c-453a-be8b-268467127d55)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复～
