### ISSUE TITLE
[小程序]官方 demo 黑屏

### ISSUE THREAD

**Issue by evenle** [leaferjs/ui#68]
[小程序]官方 demo 黑屏
https://www.leaferjs.com/ui/guide/miniapp/start.html

模拟器和安卓可以，IOS 是黑屏，也没有报错

**Comment by leaferjs** [comment]
谢谢反馈，小程序3.0版本之后主Canvas drawImage不了离屏画布的内容，ios目前在等官方修复这个bug，安卓采用了特殊的方式才能用，我们后面也会再想想办法～

**Comment by leaferjs** [comment]
已修复ios下demo黑屏问题，等待新版发布～

**Comment by leaferjs** [comment]
新版本已发布～
