### ISSUE TITLE
如何取消画布的滚轮事件？

### ISSUE THREAD

**Issue by xinglufan** [leaferjs/ui#69]
我不希望画布应用滚轮上下滚动，因为我只是想在网页中画一幅简单的示意图。
然后我根据 #7 设置成了type为draw后，确实能解决，但是当鼠标放在画布上时，滚轮就无法滚动外面的页面了
这对只是放一些示意图在网页中的网页浏览体验很不友好，希望能帮忙解答一下，谢谢！

**Comment by leaferjs** [comment]
如果希望画布还有交互，可以设置  wheel: { preventDefault: false }
