### ISSUE TITLE
对app内的leafer修改zindex无效

### ISSUE THREAD

**Issue by Alfen2309** [leaferjs/ui#70]
我在使用zIndex试图调整leafer的展示顺序，但是他好像并没有正常的工作。
无论怎么设置，leafer都按照add的顺序进行显示
例如：
1. 在app中先添加了leaferA，将其zIndex设置为5
2. 然后在app中添加leaferB，将其zIndex设置为1
3. 期望A中的元素显示在B的上方，但是实际正好相反

我还试过使用app中addAt，addBefore方法，也没有达到预期的效果，这两个方法似乎与add的效果相同。
期望得到解答，感谢

**Comment by leaferjs** [comment]
谢谢反馈～

1. App到Leafer的这一层没有走布局，所以zIndex起不了作用

2. app中addAt，addBefore方法会走add逻辑，add逻辑重写过，这次可以修复下

**Comment by Alfen2309** [comment]
感谢回复，请问有其他方式能够修改leafer的层级关系吗

**Comment by leaferjs** [comment]
视图层级可以手动修改 app.view 里canvas的顺序，每个leafer对应一块canvas,     另外再调整下app.children里leafer的顺序

**Comment by leaferjs** [comment]
已支持Leafer修改zIndex层级功能，App也支持 addAt() / addBefore() / addAfter() 方法，请关注今天的 rc.28版本发布～
