### ISSUE TITLE
请问有没有考虑过加一个将图形居中展示在视图中间的功能呢

### ISSUE THREAD

**Issue by GenieShen** [leaferjs/ui#73]
例如在leafer舞台缩放比例较小的时候，点击某个图形，将leafer放大到1倍缩放比例，并且将该图形居中展示在视图中央。现在我简单实现了一个版本，但是效果不是很好，希望官方考虑下~（另外，技术交流群二维码在哪里可以找到呢，想进群~）

**Comment by leaferjs** [comment]
谢谢反馈，有考虑的，这个属于聚焦到指定元素的功能，到时会统一做到视图操作插件中～

技术交流群的二维码在文档首页：https://www.leaferjs.com/ui/guide/

**Comment by GenieShen** [comment]
> 谢谢反馈，有考虑的，这个属于聚焦到指定元素的功能，到时会统一做到视图操作插件中～
> 
> 技术交流群的二维码在文档首页：https://www.leaferjs.com/ui/guide/

大概上线日期有嘛

**Comment by QC2168** [comment]
您好  这个功能已经上线了吗 现在还需要手动计算吗@ @leaferjs

**Comment by QC2168** [comment]
已经解决，视图居中
```
app.tree.zoom('fit', 0, true)
```
