### ISSUE TITLE
[多平台]有支持uniapp的计划么？

### ISSUE THREAD

**Issue by brankcar** [leaferjs/ui#74]
目前多平台支持只有小程序和web可用于用户端使用，请问官方是否有支持app的方案呢？比如RN或uniapp之类的

**Comment by leaferjs** [comment]
现在还不太确定，只要能支持离屏画布，一般都有办法能适配的了（底层是非常灵活的，以后还能使用webgl、webgpu渲染)，等我们主要功能做完了，会再深入做跨平台，可以先考虑使用webview方案。

**Comment by brankcar** [comment]
> 现在还不太确定，只要能支持离屏画布，一般都有办法能适配的了（底层是非常灵活的，以后还能使用webgl、webgpu渲染)，等我们主要功能做完了，会再深入做跨平台，可以先考虑使用webview方案。

目前主要担心跨端使用会造成访问DOM、BOM方法报错，如果未支持的话目前只能先使用webview

**Comment by leaferjs** [comment]
OK～

**Comment by yy8z7** [comment]
有最新的资讯了嘛

**Comment by leaferjs** [comment]
已支持～
