### ISSUE TITLE
Text文本修改fill属性的时候宽度丢失

### ISSUE THREAD

**Issue by mhrmsg** [leaferjs/ui#76]
通过修改Text的fill属性改变文本颜色，改变之前能够获取它的宽度，改变后再次获取它的宽度发现为0
复现链接：
https://codesandbox.io/p/devbox/competent-gianmarco-39n5qr?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue

**Comment by leaferjs** [comment]
收到，谢谢反馈～，没有设置宽度的文本，建议通过 text.getBounds('content', 'inner') 获取实时的内部bounds

https://leaferjs.com/ui/guide/property/bounds.html#getbounds-type-iboundstype-box-relative-ilocationtype-ui-world-iboundsdata
