### ISSUE TITLE
group的scaleY为-1翻转后,图层编辑器选后会出现错位

### ISSUE THREAD

**Issue by HeeChung** [leaferjs/ui#81]
` new Group({
            editable: true,
            scaleY: -1,
          });`

**Comment by leaferjs** [comment]
收到， 谢谢反馈～

**Comment by HeeChung** [comment]
![image](https://github.com/leaferjs/ui/assets/76504874/ba3226df-8c85-47b0-b21e-41b6dbd90c76)这个效果

**Comment by leaferjs** [comment]
已修复，等待新版本发布～
