### ISSUE TITLE
如何清空画板，多个实例案例

### ISSUE THREAD

**Issue by hmwl** [leaferjs/ui#83]
如题，感谢！

希望能够清空画板方法（开发文档中没有找到），并能支持同页面多个实例的实现思路

**Comment by leaferjs** [comment]
用removeAll(true) 清除所有元素：
https://leaferjs.com/ui/guide/display/Group.html#removeall-destroy-boolean

**Comment by leaferjs** [comment]
同页面创建多个实例，默认应该就支持，只是实例view的dom容器需要你自己控制怎么显示

**Comment by leaferjs** [comment]
增加了clear()方法，等待新版本发布～
