### ISSUE TITLE
 操作Group拉伸 Group 子元素box里面的文字布局会进行改变

### ISSUE THREAD

**Issue by xuchenxu** [leaferjs/ui#90]
操作Group拉伸 Group 子元素box里面的文字布局会进行改变
操作图： ![1708917262837](https://github.com/leaferjs/ui/assets/46715571/0fee023c-5022-4905-8ae1-b2f656b8680f)
 ![1708917262834](https://github.com/leaferjs/ui/assets/46715571/7f2a9384-0a3e-4d91-8207-6f9bb2b02bd6)
文件结构： ![image](https://github.com/leaferjs/ui/assets/46715571/3943f969-82a4-44e5-b83f-19235574eb86)

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
方便直接给一个json结构吗？我这边复现不了～， 正常情况下修改Group会影响Box的宽高，但是Box内部元素不会受影响，如果想整体互不影响，也可以把Group也改成Box
