### ISSUE TITLE
富文本元素添加到Group偶发性不显示，需其他元素触发刷新

### ISSUE THREAD

**Issue by xuchenxu** [leaferjs/ui#92]
![image](https://github.com/leaferjs/ui/assets/46715571/907b82f9-63c5-4edd-beb4-3a25a0385f9c)
![image](https://github.com/leaferjs/ui/assets/46715571/e8ca9d5d-8d3f-4a1e-b0a6-e58207a6af4e)
![image](https://github.com/leaferjs/ui/assets/46715571/c8774cb5-0f22-467f-91ee-c7f001aa8b94)

使用app.tree.forceRender()不显示几率变低

**Comment by xuchenxu** [comment]
放置图片也会有几率不显示 目前发现一个解决办法是添加一个宽高属性

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
已修复，请安装新版本rc.18验证～
