### ISSUE TITLE
键盘事件冲突

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#93]
请问键盘事件有冲突怎么解决呢，就是输入框的上下左右会影响元素的上下左右，删除监听也会被触发。

**Comment by QmagicianEX** [comment]
close

**Comment by leaferjs** [comment]
关闭交互功能： leafer.interaction.stop() 
开启交互功能： leafer.interaction.start()

**Comment by leaferjs** [comment]
如果页面不需要渲染，可以用更简单的 leafer.stop() / leafer.start()

**Comment by QmagicianEX** [comment]
![image](https://github.com/leaferjs/ui/assets/129353743/a4d22cd2-d15c-4e31-b0f3-369ef1bfa2c9)


// 删除监听，这个好像在别的输入框点击删除输入，也会被捕捉到
this.app.on(KeyEvent.DOWN, this.removeItems)
// 移除选中的元素
      removeItems(e) {
        if (e.key == 'Backspace' || e.key == 'Delete') {
          let editor = this.app.editor
          let target = editor.target
          if (editor.single) {
            editor.removeItem(target)
            this.app.tree.remove(target)
          } else {
            if (editor.multiple) {
              target.forEach(item => {
                editor.removeItem(item)
                this.app.tree.remove(item)
              })
            }
          }
        }
      },

**Comment by rojer95** [comment]
我目前是这样解决的 ~ 
```
    function onKeyDown(e: KeyEvent) {
      if (
        ["INPUT", "TEXTAREA"].includes(
          document.activeElement?.tagName as string
        )
      ) {
        e.stop();
      }
    }

    app?.on(KeyEvent.DOWN, onKeyDown, true);
```
