### ISSUE TITLE
期望功能：可以配置指定元素的固定比例缩放

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#95]
![image](https://github.com/leaferjs/ui/assets/129353743/3c5cd072-c0ae-4a63-910c-c9d2e239e639)

比如我的图标元素，可以固定比例进行缩放，其它元素可以自由缩放；

lockRatio属性貌似是辑器级别的，会对所有元素生效，元素属性没有找到类似lockRatio的配置；

也可能是我还没发现相关的配置。

**Comment by leaferjs** [comment]
收到，正有这个计划～

**Comment by leaferjs** [comment]
后续会有相关插件

**Comment by leaferjs** [comment]
元素已支持通过editConfig独立配置：

https://leaferjs.com/ui/guide/property/editable.html#editconfig-ieditorconfig
