### ISSUE TITLE
mac pixelRatio >1 导致canvas绘制图片宽高 为实际高度的 1/pixelRatio 

### ISSUE THREAD

**Issue by Tianj0o** [leaferjs/ui#96]
本地应该比较好复现，__drawAfterFill 函数貌似有点问题

**Comment by leaferjs** [comment]
收到，谢谢反馈～，Canvas元素默认使用了当前设备的像素比，造成了这个差异，后面会改成默认为1

**Comment by leaferjs** [comment]
可以强制给Canvas元素设置pixelRatio 为 1解决这个问题， 或者使用canvas的context之前，先通过setTransform抹平这个差异，再drawImage

**Comment by Tianj0o** [comment]
ok,我目前是解决方法是绘制的时候*pixelRatio
