### ISSUE TITLE
如何禁止Leafer的无限画布，目前是可以通过鼠标滑鼠一直向上向下滚动，如何禁用掉？

### ISSUE THREAD

**Issue by xpanda2017** [leaferjs/ui#98]

**Comment by leaferjs** [comment]
<img width="360" alt="image" src="https://github.com/leaferjs/ui/assets/83396016/5b6acd7a-0daa-4ac5-b54d-25b3de5f93f3">

**Comment by xpanda2017** [comment]
非常感谢，https://leaferjs.com/docs/guide/display/Leafer.html 文档里没有提到，故有此问。还有个问题这样是限制了无限向上向下，但是内容区域也无法在canvas内部滚动，我想像石墨文档一样canvas随内容区域改变完全填充，只在内容区域自由滚动，用右侧的canvas来控制滚动，请问用leafer如何实现呢？感谢🙏

**Comment by leaferjs** [comment]
可以结合MoveEvent自己控制，视窗交互的这篇文章可以看下，我们最近也会增加限制滚动范围的配置
https://leaferjs.com/ui/guide/app/window.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%A4%E4%BA%92%E6%96%B9%E5%BC%8F

**Comment by leaferjs** [comment]
增加了leafer.config.scroll = 'limit' ，来配置类似文档、网页的有限区域滚动功能，等待下个版本更新
