### ISSUE TITLE
编辑器有移动、缩放和旋转事件结束监听吗？

### ISSUE THREAD

**Issue by QmagicianEX** [leaferjs/ui#99]

**Comment by leaferjs** [comment]
有的：
https://leaferjs.com/ui/guide/plugin/editor/Event.html

**Comment by QmagicianEX** [comment]
这个是过程的吧，就是如果我想在移动事件结束后记录当前编辑器状态，以便我做撤销和恢复；
目前有的应该是元素级别的吧，是否需要每次add元素时就添加监听事件才能满足以上场景。
![image](https://github.com/leaferjs/ui/assets/129353743/9346c2c9-2bd1-4a70-a966-b32445e9d880)

**Comment by leaferjs** [comment]
这个是结束后派发的事件，历史记录可以通过全局监听属性变化事件：

https://leaferjs.com/ui/guide/plugin/editor/Editor.html#%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95

**Comment by QmagicianEX** [comment]
好的

**Comment by leaferjs** [comment]
这个事件是在编辑器上的
